### ISSUE TITLE
ClassCastException in schema generation

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1147]
From the graphql-java gitter stream :

Albert Lockett @albertlockett_twitter 

I was trying to generate an executable schema and I kept getting this ClassCastException like this:

```
Caused by: java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLInterfaceType
    at graphql.schema.idl.SchemaGenerator.lambda$buildObjectTypeInterfaces$7 (SchemaGenerator.java:377)
    at java.util.ArrayList.forEach (ArrayList.java:1378)
    at graphql.schema.idl.SchemaGenerator.buildObjectTypeInterfaces (SchemaGenerator.java:376)
    at graphql.schema.idl.SchemaGenerator.buildObjectType (SchemaGenerator.java:348)
    at graphql.schema.idl.SchemaGenerator.buildOutputType (SchemaGenerator.java:285)
    at graphql.schema.idl.SchemaGenerator.buildField (SchemaGenerator.java:469)
    at graphql.schema.idl.SchemaGenerator.lambda$buildObjectTypeFields$4 (SchemaGenerator.java:357)
```

I managed to generate a minimal schema that reproduces that stack trace:

```
interface MyInterface {
  interfaceField: MyNonImplementingType
}
type MyNonImplementingType {
  nonImplementingTypeField: MyImplementingType
}
type MyImplementingType implements MyInterface{
  interfaceField: MyNonImplementingType
}
type Query {
  hello: String
}
```

I tried making the executable schema in JS, using the reference implementation and I was able to create it.

It seems to be cause by this circular reference of:
Intreface has field of non-implemeting-type
non-implementing-type has field with type implementing-type
implementing-type implements the interface and has a field of type non-implementing-type

I posted this back in May, didn't get a hit on it. Was able to get around it by rearranging bits of the schema definition, but as my project's schema grows I keep hitting it. Was thinking could ask my boss for some time to rummage around in the graphql-java code to find the cause, but if anyone has a quick idea what could cause it that'd be helpful

**Comment by albertlockett2** [comment]
The graphql-java code that causes this runs something like this:
```
SchemaGenerator schemaGenerator = new SchemaGenerator();
// content from above is in schema.gql
Reader schemaFile = this.loadSchema("schema.gql");
GraphQLSchema schema = schemaGenerator.makeExecutableSchema(typeRegistry, wiring);
```
As far as I can tell, doesn't really matter what's in the runtime wiring

**Comment by albertlockett2** [comment]
https://github.com/albertlockett2/graphql-java-bug-example I created an example project that causes this exception. Can just `mvn test`

Here's the source from the test:
```
import graphql.TypeResolutionEnvironment;
import graphql.schema.GraphQLObjectType;
import graphql.schema.GraphQLSchema;
import graphql.schema.idl.RuntimeWiring;
import graphql.schema.idl.SchemaGenerator;
import graphql.schema.idl.SchemaParser;
import graphql.schema.idl.TypeDefinitionRegistry;

import java.io.File;

import junit.framework.Test;
import junit.framework.TestCase;
import junit.framework.TestSuite;

public class AppTest extends TestCase {

  public AppTest(String testName) {
    super(testName);
  }

  public static Test suite() {
    return new TestSuite(AppTest.class);
  }

  public GraphQLObjectType resolveType(TypeResolutionEnvironment env) {
    return (GraphQLObjectType) env.getSchema().getType("MyImplementingType"); 
  }

  public void testApp() {

    TypeDefinitionRegistry types = new SchemaParser().parse(new File("src/test/resources/schema.gql"));
    RuntimeWiring wiring = RuntimeWiring.newRuntimeWiring()
      .type("Query", typeWiring -> typeWiring.dataFetcher("hello", env -> "Hello, world"))
      .type("MyInterface", typeWiring -> typeWiring.typeResolver(this::resolveType))
      .build();

    GraphQLSchema schema = new SchemaGenerator().makeExecutableSchema(types, wiring);
    System.out.println("Hello, world!");
    assertTrue(true);
  }

}
```

Does:
````
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ca.albertlockett.AppTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.261 sec <<< FAILURE!
testApp(ca.albertlockett.AppTest)  Time elapsed: 0.252 sec  <<< ERROR!
java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLInterfaceType
	at graphql.schema.idl.SchemaGenerator.lambda$buildObjectTypeInterfaces$7(SchemaGenerator.java:381)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at graphql.schema.idl.SchemaGenerator.buildObjectTypeInterfaces(SchemaGenerator.java:380)
	at graphql.schema.idl.SchemaGenerator.buildObjectType(SchemaGenerator.java:373)
	at graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:296)
	at graphql.schema.idl.SchemaGenerator.buildField(SchemaGenerator.java:544)
	at graphql.schema.idl.SchemaGenerator.lambda$buildObjectType$4(SchemaGenerator.java:362)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at graphql.schema.idl.SchemaGenerator.buildObjectType(SchemaGenerator.java:361)
	at graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:296)
	at graphql.schema.idl.SchemaGenerator.buildField(SchemaGenerator.java:544)
	at graphql.schema.idl.SchemaGenerator.lambda$buildInterfaceType$10(SchemaGenerator.java:411)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at graphql.schema.idl.SchemaGenerator.buildInterfaceType(SchemaGenerator.java:410)
	at graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:298)
	at graphql.schema.idl.SchemaGenerator.lambda$buildAdditionalTypes$3(SchemaGenerator.java:261)
	at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608)
	at graphql.schema.idl.SchemaGenerator.buildAdditionalTypes(SchemaGenerator.java:253)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchemaImpl(SchemaGenerator.java:230)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:176)
	at ca.albertlockett.AppTest.testApp(AppTest.java:39)
```
