### ISSUE TITLE
Query for introspection field  __typename throws an exception if MaxQueryComplexityInstrumentation is used

### ISSUE THREAD

**Issue by vojtechmasa** [graphql-java/graphql-java#1200]
If `MaxQueryComplexityInstrumentation` is used - my setup is as the following:

    GraphQL.newGraphQL(schema)
        .queryExecutionStrategy(queryExecutionStrategy())
        .mutationExecutionStrategy(mutationExecutionStrategy())
        .instrumentation(
                new MaxQueryComplexityInstrumentation(MAX_FIELDS_IN_QUERY)
        )
        .build();

any query containing `__typename` introspection field throws the following exception:

    java.lang.IllegalStateException: introspection field __typename doesn't have a fields container
	at graphql.analysis.QueryVisitorFieldEnvironmentImpl.getFieldsContainer(QueryVisitorFieldEnvironmentImpl.java:76) ~[graphql-java-10.0.jar!/:na]
	at graphql.analysis.MaxQueryComplexityInstrumentation.convertEnv(MaxQueryComplexityInstrumentation.java:111) ~[graphql-java-10.0.jar!/:na]
	at graphql.analysis.MaxQueryComplexityInstrumentation.calculateComplexity(MaxQueryComplexityInstrumentation.java:99) ~[graphql-java-10.0.jar!/:na]
	at graphql.analysis.MaxQueryComplexityInstrumentation.access$000(MaxQueryComplexityInstrumentation.java:22) ~[graphql-java-10.0.jar!/:na]
	at graphql.analysis.MaxQueryComplexityInstrumentation$1.visitField(MaxQueryComplexityInstrumentation.java:65) ~[graphql-java-10.0.jar!/:na]
	at graphql.analysis.QueryTraversal$NodeVisitorImpl.visitField(QueryTraversal.java:271) ~[graphql-java-10.0.jar!/:na]
	at graphql.language.Field.accept(Field.java:165) ~[graphql-java-10.0.jar!/:na]
	at graphql.language.NodeTraverser$1.leave(NodeTraverser.java:72) ~[graphql-java-10.0.jar!/:na]
	at graphql.util.Traverser.traverse(Traverser.java:83) ~[graphql-java-10.0.jar!/:na]
	at graphql.language.NodeTraverser.doTraverse(NodeTraverser.java:151) ~[graphql-java-10.0.jar!/:na]
	at graphql.language.NodeTraverser.depthFirst(NodeTraverser.java:76) ~[graphql-java-10.0.jar!/:na]
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:178) ~[graphql-java-10.0.jar!/:na]
	at graphql.analysis.QueryTraversal.visitPostOrder(QueryTraversal.java:96) ~[graphql-java-10.0.jar!/:na]
	at graphql.analysis.MaxQueryComplexityInstrumentation.lambda$beginValidation$1(MaxQueryComplexityInstrumentation.java:58) ~[graphql-java-10.0.jar!/:na]
	at graphql.execution.instrumentation.SimpleInstrumentationContext.onCompleted(SimpleInstrumentationContext.java:37) ~[graphql-java-10.0.jar!/:na]
	at graphql.execution.instrumentation.ChainedInstrumentation$ChainedInstrumentationContext.lambda$onCompleted$1(ChainedInstrumentation.java:237) ~[graphql-java-10.0.jar!/:na]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378) ~[na:na]
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1081) ~[na:na]
	at graphql.execution.instrumentation.ChainedInstrumentation$ChainedInstrumentationContext.onCompleted(ChainedInstrumentation.java:237) ~[graphql-java-10.0.jar!/:na]
	at graphql.GraphQL.validate(GraphQL.java:541) ~[graphql-java-10.0.jar!/:na]
	at graphql.GraphQL.parseAndValidate(GraphQL.java:509) ~[graphql-java-10.0.jar!/:na]
	at graphql.GraphQL.lambda$parseValidateAndExecute$3(GraphQL.java:490) ~[graphql-java-10.0.jar!/:na]
	at graphql.execution.preparsed.NoOpPreparsedDocumentProvider.get(NoOpPreparsedDocumentProvider.java:11) ~[graphql-java-10.0.jar!/:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:486) ~[graphql-java-10.0.jar!/:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:470) ~[graphql-java-10.0.jar!/:na]
	at graphql.GraphQL.execute(GraphQL.java:401) ~[graphql-java-10.0.jar!/:na]
	at graphql.GraphQL.execute(GraphQL.java:371) ~[graphql-java-10.0.jar!/:na]

Specifically, my query looks similarly like `{payment(id: 152) {specificSymbol __typename}}`.
This query works without problem in version `9.3` using `MaxQueryComplexityInstrumentation`.

**Comment by bbakerman** [comment]
Yikes... That seems bad... We will look ASAP

**Comment by bbakerman** [comment]
Yup replicated it via unit test - will look into why this is happening.  Expect a 10.1 soon enough I think

**Comment by bbakerman** [comment]
@andimarek  - you added new code as part of your query traversal refactor

```
    @Override
    public GraphQLFieldsContainer getFieldsContainer() {
        if (isTypeNameIntrospectionField()) {
            throw new IllegalStateException("introspection field __typename doesn't have a fields container");
        }
        return unmodifiedParentType;
    }
```

Which is explcitly asserting that _typename can be used during query traversal?  Not sure why??

**Comment by bbakerman** [comment]
```
            boolean isTypeNameIntrospectionField = fieldDefinition == Introspection.TypeNameMetaFieldDef;
            GraphQLFieldsContainer fieldsContainer = !isTypeNameIntrospectionField ? (GraphQLFieldsContainer) unwrapAll(parentEnv.getOutputType()) : null;
            Map<String, Object> argumentValues = valuesResolver.getArgumentValues(schema.getFieldVisibility(), fieldDefinition.getArguments(), field.getArguments(), variables);
            QueryVisitorFieldEnvironment environment = new QueryVisitorFieldEnvironmentImpl(isTypeNameIntrospectionField,
                    field,
                    fieldDefinition,
                    parentEnv.getOutputType(),
                    fieldsContainer,
                    parentEnv.getEnvironment(),
                    argumentValues,
                    parentEnv.getSelectionSetContainer());

```

**Comment by andimarek** [comment]
I guess there is just an explicit check for `isTypeNameIntrospectonField` missing:
@bbakerman the code was added because` __typename` is the only field which is not contained in the parent field container, therefore you can't get the fieldsContainer.

**Comment by alexgenco** [comment]
Will there be a point release for this soon? We upgraded to 10.0 recently and would prefer to roll forward than backward.
