### ISSUE TITLE
Cursor, Datetime, Node missing?

### ISSUE THREAD

**Issue by xenoterracide** [graphql-java/graphql-java#1274]
Sorry this may not be a bug... are these supposed to be there? they don't seem like "custom" types
```
Caused by: graphql.schema.idl.errors.SchemaProblem: errors=[There is no scalar implementation for the named  'Cursor' scalar type, There is no scalar implementation for the named  'Datetime' scalar type, There is no type resolver defined for interface / union 'Node' type]
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:270) ~[graphql-java-10.0.jar:na]
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:246) ~[graphql-java-10.0.jar:na]
```

**Comment by bbakerman** [comment]
In your SDL you need to define custom scalars.  Datetime and Cursor are not scalars provided by graphql-java

You would need to declare the in SDL AND provide an implementation

```
scalar Datetime

type SomeType {
   created : Datetime
}
```

This is not a bug in graphql-java per se.

How are you creating your schema?

**Comment by xenoterracide** [comment]
I believe it was generated by introspection via Postgraphile.

**Comment by xenoterracide** [comment]
it may be of interest.... apollo-android generates java classes, but when it looks at the schema, it only generates the one you need for you query, maybe there could be an import like/ish this...

**Comment by xenoterracide** [comment]
also I tried doing this (and Instant), with the extended types available at runtime... but it's still saying I need to implement the class (note, I modified types too)

```
scalar DateTime
```

**Comment by bbakerman** [comment]
Have a look at https://github.com/graphql-java/graphql-java-extended-scalars which has an implemented DateTime scalar

Also read the documentation on schemas here about how you wire in that implementation

https://www.graphql-java.com/documentation/v10/schema/

**Comment by xenoterracide** [comment]
```
Exception in thread "Apollo Dispatcher" java.lang.IllegalArgumentException: Can't map GraphQL type: Datetime to: class java.lang.Object. Did you forget to add custom type adapter?
	at com.apollographql.apollo.response.ScalarTypeAdapters.adapterFor(ScalarTypeAdapters.java:29)
	at com.apollographql.apollo.internal.json.InputFieldJsonWriter.writeCustom(InputFieldJsonWriter.java:83)
```
hmmm.... 

```
    GraphQLSchema schema( @Value( "classpath:schema.graphqls" ) Reader schema ) {
        TypeDefinitionRegistry typeDefs = new SchemaParser().parse( schema );
        RuntimeWiring wiring
                = RuntimeWiring.newRuntimeWiring()
                .scalar( new DateTimeScalar() )
                .build();
        return new SchemaGenerator().makeExecutableSchema( typeDefs, wiring );
    }
````

so that isn't enough?

**Comment by xenoterracide** [comment]
oh nvm, that exception is coming from apollo, still that documentation could be clearer... I presume this is the actual right way to do it.

```
    GraphQLSchema schema( @Value( "classpath:schema.graphqls" ) Reader schema ) {
        TypeDefinitionRegistry typeDefs = new SchemaParser().parse( schema );
        RuntimeWiring wiring
                = RuntimeWiring.newRuntimeWiring()
                .scalar( ExtendedScalars.newAliasedScalar( "Datetime" )
                        .aliasedScalar( ExtendedScalars.DateTime ).build() )
                .build();
        return new SchemaGenerator().makeExecutableSchema( typeDefs, wiring );
    }
```
