### ISSUE TITLE
Version 11 exception with GraphQLTypeReference

### ISSUE THREAD

**Issue by LarsKrogJensen** [graphql-java/graphql-java#1287]
Upgrading a project from version 10 to 11 causes exception when GraphQLTypeReference are used:

`java.lang.ClassCastException: class graphql.schema.GraphQLTypeReference cannot be cast to class graphql.schema.GraphQLUnmodifiedType (graphql.schema.GraphQLTypeReference and graphql.schema.GraphQLUnmodifiedType are in unnamed module of loader 'app')
	at graphql.schema.GraphQLTypeUtil.unwrapAll(GraphQLTypeUtil.java:169)
	at graphql.schema.GraphQLTypeUtil.isLeaf(GraphQLTypeUtil.java:122)
	at graphql.validation.rules.ScalarLeafs.checkField(ScalarLeafs.java:23)
	at graphql.validation.RulesVisitor.checkField(RulesVisitor.java:117)
	at graphql.validation.RulesVisitor.enter(RulesVisitor.java:71)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:33)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:38)
	at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:28)
	at graphql.validation.Validator.validateDocument(Validator.java:42)
	at graphql.GraphQL.validate(GraphQL.java:558)
	at graphql.GraphQL.parseAndValidate(GraphQL.java:528)
       ....
`

Also the introspection query that GraphiQL is sending is causing exceptions, that also seems related to the type reference
`16:02:53.647 [vert.x-eventloop-thread-2] WARN  g.e.SimpleDataFetcherExceptionHandler - Exception while fetching data (/__schema/types[13]/fields[1]/type/ofType/kind) : Internal error: should never happen: Unknown kind of type: graphql.schema.GraphQLTypeReference@9c62d8e
graphql.AssertException: Internal error: should never happen: Unknown kind of type: graphql.schema.GraphQLTypeReference@9c62d8e
	at graphql.Assert.assertShouldNeverHappen(Assert.java:26)
	at graphql.introspection.Introspection.lambda$static$0(Introspection.java:90)
	at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:261)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:202)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:70)
        ...
`

**Comment by andimarek** [comment]
thanks ... we will look into it.

**Comment by andimarek** [comment]
@LarsKrogJensen I initially read it as a Java 11 problem. But you mean you updated from graphql-java 10 to 11, right?
Which java version are you using?
thanks

**Comment by LarsKrogJensen** [comment]
@andimarek  Sorry for being unclear, but you are correct - I upgraded a project from graphql-java 10 to 11.
Project is currently using java 11.

**Comment by bbakerman** [comment]
@LarsKrogJensen  - any chance you can give is a unit test / SDL schema so we can try to reproduce.

I am unsure how you are using GraphQLTypeReference and hence how this is blowing up.

nominally the schema type references SHOULD be all removed on schema creation time via `graphql.schema.SchemaUtil#replaceTypeReferences` but perhaps they are not.

Any chance you can gives us a test reproduction helper

**Comment by LarsKrogJensen** [comment]
Sure, will try to create a reproducer.

**Comment by arlampin** [comment]
Something to do with #1216 maybe?

**Comment by LarsKrogJensen** [comment]
Thanx for the hint, will try that.

Spent a few hours on trying to create a simple reproducer, but failed so far. I'll continue.

**Comment by LarsKrogJensen** [comment]
#1216 might indeed be related, unsure how yet.

**Comment by LarsKrogJensen** [comment]
Can confirm this issue is the same a #1216. Now that I know what is causing it I can work around it, closing as duplicate. Thanks for the responses, I should have look harder for known issues.  :(

**Comment by bbakerman** [comment]
Hmnmm I think this behaviour should be fixed.  I will do it in terms of the other issue (because its a better desciption of the problem).

But the behaviour of re-using type refs is not wrong
