### ISSUE TITLE
UNION location seems to always be ignored.

### ISSUE THREAD

**Issue by zcourts** [graphql-java/graphql-java#1296]
I have a directive declared as
```directive @src(publisherRealm: String, name: String, version: String) on INTERFACE | OBJECT | INPUT_OBJECT | ENUM | SCALAR | FIELD_DEFINITION | UNION
```
In all cases listed, it appears to work, except for unions. In which case it fails with
```
Caused by: SchemaProblem{errors=['HypiEntity' [@1:1] tried to use a directive 'src' in the 'UNION' location but that is illegal]}
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:267)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:246)
	at io.hypi.davil.gql.AppReleaseCtx.traverseModel(AppReleaseCtx.java:260)
	at io.hypi.davil.gql.data.AppReleaseManager.load(AppReleaseManager.java:87)
	at io.hypi.davil.SystemBootstrap.lambda$onApplicationEvent$2(SystemBootstrap.java:109)
	... 16 more
```

**Comment by bbakerman** [comment]
I wrote this quick reproduction test (spock+groovy) but could not find a problem

```
        def spec = '''
            directive @src(publisherRealm: String, name: String, version: String) on INTERFACE | OBJECT | INPUT_OBJECT | ENUM | SCALAR | FIELD_DEFINITION | UNION

            type Foo @src(publisherRealm : "x", name : "y", version : "Foo") {
                foo : String
            }

            type Bar @src(publisherRealm : "x", name : "y", version : "Bar") {
                bar : String
            }

            union UnionType @src(publisherRealm : "x", name : "y", version : "U") =  Foo | Bar

            type Query {
                f1 : UnionType @src(publisherRealm : "x", name : "y", version : "v") 
            }
        '''

        def registry = parse(spec)
        def errors = []

        when:
        new SchemaTypeDirectivesChecker(registry, RuntimeWiring.newRuntimeWiring().build()).checkTypeDirectives(errors)

        then:
        errors.size() == 0

        when:
        def schema = TestUtil.schema(spec)
        then:
        noExceptionThrown()
```

This was on master (not on a released version so perhaps its been fixed since)

Any chance you can create a production unit test on the version your are using?

**Comment by bbakerman** [comment]
`graphql.schema.idl.SchemaTypeDirectivesCheckerTest` has test case for unions and others for the record

**Comment by zcourts** [comment]
Yup, I'll put one together. I'm at a conference this week so may be tight on time but back home weekend so I will do it then.

**Comment by bbakerman** [comment]
Any news on this??

**Comment by zcourts** [comment]
Got back yesterday haven't had time yet, will send reproducer this week

**Comment by bbakerman** [comment]
Any more news on this issue?

Just doing my periodic review of open issues and wanted top ping this one
