### ISSUE TITLE
TypeResolver is not working as expected in v12

### ISSUE THREAD

**Issue by ahboujelben** [graphql-java/graphql-java#1522]
Hello,

We're trying to upgrade to v12 from v11. We're using an interface called 'DataModel' in the graphql schema and we add its type resolver in the runtime wiring as described in the documentation. 
```java
 private static RuntimeWiring buildRuntimeWiring()
  {
return RuntimeWiring.newRuntimeWiring()
        .type( "Query", typeWiring -> typeWiring
            .dataFetcher( "projects", QueryResolver.getProjectsDataFetcher() ) )
.
.
.
        .type( "DataModel", typeWiring -> typeWiring
            .typeResolver( DataModelResolver.getTypeResolver() ) )
.
.
.
        .build();
}
```
The type resolver is implemented like this:

```java
  public static TypeResolver getTypeResolver()
  {
    return new TypeResolver()
    {
      @Override
      public GraphQLObjectType getType( final TypeResolutionEnvironment env )
      {
        Object javaObject = env.getObject();
        if ( javaObject instanceof GraphqlRun )
        {
          return env.getSchema().getObjectType( "Run" );
        }
        else
        {
          return env.getSchema().getObjectType( "History" );
        }
      }
    };
  }

```

The schema is created and configured inside GraphQLHttpServlet as follows: 

``` java
@Override
  protected GraphQLConfiguration getConfiguration()
  {
    return GraphQLConfiguration.with( createSchema() ).with( createQueryInvoquer() ).build();
  }

  private static GraphQLSchema createSchema()
  {
    Reader reader = new InputStreamReader(
        GraphqlServlet.class.getClassLoader().getResourceAsStream( "graphql/schema.graphqls" ),
        StandardCharsets.UTF_8 );

    SchemaParser schemaParser = new SchemaParser();
    TypeDefinitionRegistry typeDefinitionRegistry = schemaParser.parse( reader );
    RuntimeWiring runtimeWiring = buildRuntimeWiring();
    SchemaGenerator schemaGenerator = new SchemaGenerator();
    return schemaGenerator.makeExecutableSchema( typeDefinitionRegistry, runtimeWiring );
  }
```
This used to work properly in v11. But after the upgrade, graphql queries result in an exception stating that 'There must be a type resolver for interface DataModel' which is not very helpful as we already provide it.

The exception looks like this:
'
org.eclipse.jetty.servlet.ServletHolder$1: graphql.AssertException: There must be a type resolver for interface DataModel
	at org.eclipse.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:575)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:639)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:477)
	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:754)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:578)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1114)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1048)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:302)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:245)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.base/java.lang.Thread.run(Thread.java:844)

**************************

Caused by: graphql.AssertException: There must be a type resolver for interface DataModel
	at graphql.Assert.assertNotNull(Assert.java:15)
	at graphql.schema.GraphQLCodeRegistry.getTypeResolverForInterface(GraphQLCodeRegistry.java:117)
	at graphql.schema.GraphQLCodeRegistry.access$700(GraphQLCodeRegistry.java:28)
	at graphql.schema.GraphQLCodeRegistry$Builder.getTypeResolver(GraphQLCodeRegistry.java:208)
	at graphql.schema.CodeRegistryVisitor.visitGraphQLInterfaceType(CodeRegistryVisitor.java:40)
	at graphql.schema.GraphQLInterfaceType.accept(GraphQLInterfaceType.java:153)
	at graphql.schema.TypeTraverser$TraverserDelegateVisitor.enter(TypeTraverser.java:71)
	at graphql.util.Traverser.traverse(Traverser.java:144)
	at graphql.schema.TypeTraverser.doTraverse(TypeTraverser.java:58)
	at graphql.schema.TypeTraverser.depthFirst(TypeTraverser.java:50)
	at graphql.schema.TypeTraverser.depthFirst(TypeTraverser.java:38)
	at graphql.schema.SchemaUtil.extractCodeFromTypes(SchemaUtil.java:112)
	at graphql.schema.GraphQLSchema$Builder.lambda$build$1(GraphQLSchema.java:413)
	at graphql.schema.GraphQLCodeRegistry.transform(GraphQLCodeRegistry.java:139)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:413)
	at graphql.servlet.GraphQLSchemaProvider.copyReadOnly(GraphQLSchemaProvider.java:15)
	at graphql.servlet.DefaultGraphQLSchemaProvider.<init>(DefaultGraphQLSchemaProvider.java:17)
	at graphql.servlet.GraphQLConfiguration.with(GraphQLConfiguration.java:22)
	at com.roxar.tempest.server.GraphqlServlet.getConfiguration(GraphqlServlet.java:40)
	at graphql.servlet.AbstractGraphQLHttpServlet.init(AbstractGraphQLHttpServlet.java:110)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:621)
	... 23 common frames omitted
'

I'm wondering what could be causing this.

Many thanks.

**Comment by bbakerman** [comment]
All of the code you have presented looks about right in graphql-java terms.

Type Resolvers have not changed in graphql 12 however the CodeRegistry idea has.  But your code is using the right RuntimeWiring so not sure???

There must be some interplay during Schema building in graphql servlet whereby its losing the type resolvers during build time.

I would ask a question on https://github.com/graphql-java-kickstart/graphql-java-servlet which is not part of this project per se.  Their project says they support v11 so perhaps they do something that is in compatible with v12??

**Comment by andimarek** [comment]
closing this issue now @ahboujelben if this issue is still a problem please open it again with new information.
