### ISSUE TITLE
ConcurrentModificationException when trying to print schema

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#1709]
**Describe the bug**

https://spectrum.chat/graphql-java/general/concurrentmodificationexception-when-trying-to-print-schema~6dafd1b9-2f62-4fec-a01e-ef824ec7598c

 am using graphql-kotlin to generate my schema from the code and when I try to produce the string version of the schema I am getting a ConcurrentModificationException. Here is the relevant stack trace.

```
java.util.ConcurrentModificationException: null
    at java.base/java.util.HashMap.computeIfAbsent(Unknown Source)
    at graphql.schema.idl.SchemaPrinter.printer(SchemaPrinter.java:691)
    at graphql.schema.idl.SchemaPrinter.printType(SchemaPrinter.java:721)
    at graphql.schema.idl.SchemaPrinter.lambda$printType$19(SchemaPrinter.java:717)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
    at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
    at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
    at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
    at graphql.schema.idl.SchemaPrinter.printType(SchemaPrinter.java:717)
    at graphql.schema.idl.SchemaPrinter.print(SchemaPrinter.java:247)
    at com.expediagroup.graphql.extensions.GraphQLSchemaExtensionsKt.print(GraphQLSchemaExtensions.kt:54)
    at com.expediagroup.graphql.extensions.GraphQLSchemaExtensionsKt.print$default(GraphQLSchemaExtensions.kt:43)
    at com.appdetex.waits.graphql.rest.GraphqlApiController.sdl(GraphqlApiController.kt:57)

```

The graphql-kotlin extension doesn't really do anything special when calling the SchemaPrinter, so I don't suspect it currently. The code at SchemaPrinter:247 is:
printType(out, typesAsList, GraphQLScalarType.class, visibility);
and I am using graphql-java-extended-scalars to register a JsonScalar.
One last wrinkle. It's only failing when I deploy it to AWS. I can run it locally, or run unit tests, and those work just fine. I am at a bit of a loss as to what is causing the exception at the moment. Any insight anybody might have is appreciated. I'm just hoping that someone might be able to point me in the right direction.

**To Reproduce**

As stated above

**Comment by andimarek** [comment]
This is fixed with #1741
