### ISSUE TITLE
at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:151) ~[graphql-java-3.0.0.jar:na]

### ISSUE THREAD

**Issue by soumyadip007** [graphql-java/graphql-java#1824]
If you have a general question or seeking advice how to use something please create a new topic in our spectrum chat: https://spectrum.chat/graphql-java Thanks
Caused by: graphql.schema.idl.errors.SchemaProblem: null
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:151) ~[graphql-java-3.0.0.jar:na]
	at com.ga4gh.prototype.graphql.service.GraphQLService.loadSchema(GraphQLService.java:51) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_151]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_151]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	... 23 common frames omitted

**Comment by andimarek** [comment]
I am sorry but this is not an acceptable issue: you are not asking any question, you are not even cleaning up the template. closing this.
