### ISSUE TITLE
An objectTypeExtension, whose value list size is zero, throws IndexOutOfBoundsError

### ISSUE THREAD

**Issue by ddold** [graphql-java/graphql-java#1885]
**Describe the bug**

I was extending a type, say `Foo`, that was added to [objectTypeExtensions](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java#L52), with the key being `Foo` and the value, `ObjectTypeExtensionDefinition`, appended to the list.
I then tried to remove the `Foo` extension by calling [remove](https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java#L239), passing in the correct `ObjectTypeExtensionDefinition`. 
While debugging, I noticed that the `Foo` entry still existed in `objectTypeExtensions` and the value was an empty list. 
This then caused an `IndexOutOfBoundsError`
```
2020-04-28 15:49:12,981 ERROR [jav.ws.rs.ext.ExceptionMapper] (executor-thread-1) Index: 0, Size: 0: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at graphql.schema.idl.SchemaTypeExtensionsChecker.checkTypeExtensionHasCorrespondingType(SchemaTypeExtensionsChecker.java:299)
	at graphql.schema.idl.SchemaTypeExtensionsChecker.lambda$checkObjectTypeExtensions$12(SchemaTypeExtensionsChecker.java:72)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at graphql.schema.idl.SchemaTypeExtensionsChecker.checkObjectTypeExtensions(SchemaTypeExtensionsChecker.java:71)
	at graphql.schema.idl.SchemaTypeExtensionsChecker.checkTypeExtensions(SchemaTypeExtensionsChecker.java:50)
	at graphql.schema.idl.SchemaTypeChecker.checkTypeRegistry(SchemaTypeChecker.java:74)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:259)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:237)
```

There should be a way for the user to be able to remove an entry via the key i.e. `remove("Foo")` and then that entry would be removed from `objectTypeExtensions`
Or else if there is a value that has a list size of 0, then that entry should be removed

**To Reproduce**
Please provide a code example or even better a test to reproduce the bug.
1. Extend a type and merge it to the `TypeDefinitionRegistry`
2. Remove the `ObjectTypeExtensionDefinition` by calling `TypeDefitionRegistry.remove()`

**Comment by ddold** [comment]
PR - https://github.com/graphql-java/graphql-java/pull/1886
