### ISSUE TITLE
NPE in SchemaTranformer on schema's with `union` types

### ISSUE THREAD

**Issue by stephenc** [graphql-java/graphql-java#1928]
**Describe the bug**

Seems like a reference is not being updated in union types when one of the component object types is being updated.

**To Reproduce**

Here is a failing test case:

```groovy
    def "failing"() {
        given:

        def internalNoteHider = new GraphQLTypeVisitorStub() {
            @Override
            TraversalControl visitGraphQLDirective(GraphQLDirective node,
                                                   TraverserContext<GraphQLSchemaElement> context) {
                if ("internalnote".equals(node.getName())) {
                    TreeTransformerUtil.deleteNode(context);
                }
                return TraversalControl.CONTINUE;
            }
        }

        GraphQLSchema schema = TestUtil.schema("""
            directive @internalnote(doc: String!) on OBJECT | FIELD_DEFINITION
            
            type Query {
                fooBar: Foo
            }
            
            interface Manchu @internalnote(doc:"...") {
              id: ID!
            }
            
            type Foo implements Manchu {
              id: ID!
            }
            
            type Bar @internalnote(doc:"...") {
              id: ID! 
              hidden: String! 
            }
          
            union FooBar = Foo | Bar
        """)

        when:
        def output = SchemaTransformer.transformSchema(schema, internalNoteHider)

        then:
        output.getType("FooBar") != null;
    }
```

This gives the following stack trace:

```
java.lang.NullPointerException
	at graphql.util.FpKit.map(FpKit.java:139)
	at graphql.schema.SchemaTransformer.lambda$getDeepestZippers$1(SchemaTransformer.java:267)
	at java.util.stream.Collectors.lambda$groupingBy$45(Collectors.java:907)
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at graphql.util.FpKit.groupingBy(FpKit.java:42)
	at graphql.schema.SchemaTransformer.getDeepestZippers(SchemaTransformer.java:265)
	at graphql.schema.SchemaTransformer.toRootNode(SchemaTransformer.java:207)
	at graphql.schema.SchemaTransformer.transform(SchemaTransformer.java:176)
	at graphql.schema.SchemaTransformer.transformSchema(SchemaTransformer.java:112)
```

We can change the _input_ schema to get the test to pass:

1. Move the `union` above `Bar`
2. Move the `interface` after the `union`
3. Remove one of the directives from either the interface or the type. The issue seems to be where both are changing at the same time

**Comment by andimarek** [comment]
this will be fixed by #2078
