### ISSUE TITLE
Random "graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLUnmodifiedType"

### ISSUE THREAD

**Issue by ceronman** [graphql-java/graphql-java#193]
Hello.

I'm not completely sure if this is an issue of `graphql-java-annotations` or `graphql-java`. I am cross posting the issue just in case. I apologize if this causes inconveniences.

I'm having the error described in the title randomly with this simple recursive schema:

``` java
public class Building {
        private String name;

        public Building(String name) {
            this.name = name;
        }

        @GraphQLField
        @GraphQLName("name")
        public String getName() {
            return name;
        }

        @GraphQLField
        @GraphQLName("apartments")
        public List<Apartment> getApartments() {
            List<Apartment> apartments = new ArrayList();
            apartments.add(new Apartment(this, "one", 10));
            apartments.add(new Apartment(this, "two", 20));
            apartments.add(new Apartment(this, "three", 30));
            return apartments;
        }
}

public class Apartment {
    private String name;
    private Integer size;
    private Building building;

    public Apartment(Building building, String name, Integer size) {
        this.building = building;
        this.name = name;
        this.size = size;
        this.building = building;
    }

    @GraphQLField
    @GraphQLName("building")
    public Building getBuilding() {
        return building;
    }

    @GraphQLField
    @GraphQLName("size")
    public Integer getSize() {
        return size;
    }

    @GraphQLField
    @GraphQLName("name")
    public String getName() {
        return name;
    }
}

public class Query {
    @GraphQLField
    public static Building building() {
        return new Building("Building");
    }

    @GraphQLField
    public static Apartment apartment() {
        return new Apartment(new Building("New building"), "New apartment", 20);
    }
}
```

I'm running it in this way:

``` java
public static void main(String[] args) throws Exception {
        GraphQLObjectType annotationsType = GraphQLAnnotations.object(Query.class);
        GraphQLSchema schema = GraphQLSchema.newSchema()
                .query(annotationsType)
                .build();
        Object result = new GraphQL(schema).execute("{ building { apartments { name, building { name } } } }").getData();

        System.out.println(result);
    }
```

The problem I have is that the test here runs okay 9 out of 10 times aprox. However, every once in a while, I get the following exception:

```
Exception in thread "main" java.lang.ClassCastException: graphql.schema.GraphQLTypeReference cannot be cast to graphql.schema.GraphQLUnmodifiedType
    at graphql.schema.SchemaUtil.getUnmodifiedType(SchemaUtil.java:30)
    at graphql.schema.SchemaUtil.isLeafType(SchemaUtil.java:12)
    at graphql.validation.rules.ScalarLeafs.checkField(ScalarLeafs.java:21)
    at graphql.validation.RulesVisitor.checkField(RulesVisitor.java:92)
    at graphql.validation.RulesVisitor.enter(RulesVisitor.java:51)
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:19)
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:22)
    at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:14)
    at graphql.validation.Validator.validateDocument(Validator.java:20)
    at graphql.GraphQL.execute(GraphQL.java:73)
    at graphql.GraphQL.execute(GraphQL.java:55)
    at graphql.GraphQL.execute(GraphQL.java:47)
    at graphql.GraphQL.execute(GraphQL.java:43)
    at GraphQLTest.main(GraphQLTest.java:63)
```

I believe this has to do with the order in which `graphql-java-annotations` processes the annotations of the `Query` class. When I print `schema.getAllTypesAsList()` I noticed that every time the error happens, the `Apartment` type appears before the `Building` type.

I am using the following versions:

```
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java</artifactId>
            <version>2016-08-21T01-09-05</version>
        </dependency>
        <dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java-annotations</artifactId>
            <version>0.9.0</version>
        </dependency>
```

Sorry for not having a concrete test case, but as I said before, this is something that happens randomly. Please let me know if you need more details.

**Comment by ceronman** [comment]
After discussing this with @yrashk from `graphql-java-annotations`, he mentioned that this might be a duplicate of #118. I have tried pull request #123 and the patch indeed fixed my issue. I hope it could get merged soon.

**Comment by dminkovsky** [comment]
#123 was merged a few days ago. @ceronman Do you think that takes care of this issue?
