### ISSUE TITLE
[v15.0 error] The field type 'Long' is not present when resolving type

### ISSUE THREAD

**Issue by hudingchen** [graphql-java/graphql-java#1948]
root.graphql
```
type Query {

}

type Mutation {

}

type Empty {
    _: String
}

input PageInput {
    pageNum: Int
    pageSize: Int
}

type Page {
    pageNum: Int
    pageSize: Int
    startRow: Int
    endRow: Int
    totalCount: Long
    totalPages: Int
    firstPage: Boolean
    lastPage: Boolean
    hasPreviousPage: Boolean
    hasNextPage: Boolean
}
```

When I upgrade the graphql-java version from 14.0 to 15.0, an error appears：
```
Caused by: graphql.schema.idl.errors.SchemaProblem: errors=[The field type 'Long' is not present when resolving type 'Page' [@18:1]]
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:251)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:227)
```

**Comment by hudingchen** [comment]
Sorry I found the answer
https://github.com/graphql-java/graphql-java-extended-scalars
