### ISSUE TITLE
NPE in CacheProvider caused by adding default values for variables

### ISSUE THREAD

**Issue by aoudiamoncef** [graphql-java/graphql-java#2084]
Hi @bbakerman @andimarek,

I implemented a CacheProvider:

```java
public class CacheProvider implements PreparsedDocumentProvider {

    @Resource
    private Cache<String, PreparsedDocumentEntry> cache;

    @Override
    public PreparsedDocumentEntry getDocument(final ExecutionInput executionInput,
            final Function<ExecutionInput, PreparsedDocumentEntry> computeFunction) {

        final Function<String, PreparsedDocumentEntry> mapCompute = key -> {
            try {
                return computeFunction.apply(executionInput);
            } catch (Exception e) {
                throw new IllegalArgumentException(String.format("Failed to compute cache key for query: %s . variables: %s",
                        executionInput.getQuery(), executionInput.getVariables()));
            }
        };

        return cache.get(executionInput.getQuery(), mapCompute);
    }

}
```
I got a NPE when I call `computeFunction.apply(executionInput)` with this kind of queries:

```graphql
query search($texte: String = "", $includetest: Boolean = true){
  search(query: $texte) {
	  test @include(if: $includetest){
	      ...testFragment
	  }
  }
}
```
Variables:
```json
{
    "texte": "work"
}
```
If I add `includetest` in my variables, it works. Is it the expected behavior ?

```
Default variables 
Default values can also be assigned to the variables in the query by adding the default value after the type declaration.

query HeroNameAndFriends($episode: Episode = JEDI) {
  hero(episode: $episode) {
    name
    friends {
      name
    }
  }
}
When default values are provided for all variables, you can call the query without passing any variables. If any variables are passed as part of the variables dictionary, they will override the defaults.
```

Infos:
```xml
  <caffeine.version>2.8.6</caffeine.version>
  <graphql-java.version>15.0</graphql-java.version>
```

Thanks

**Comment by bbakerman** [comment]
Can you provide the stack trace for the NPE - we cant see where the NPE is

**Comment by aoudiamoncef** [comment]
Hi @bbakerman,
I found the potential issue:
```java
        if (instrumentation.getQueryComplexity().isEnabled()) {
            instrumentations
                    .add(new MaxQueryComplexityInstrumentation(instrumentation.getQueryComplexity().getComplexity()));
        }
        if (instrumentation.getQueryDepth().isEnabled()) {
            instrumentations.add(new MaxQueryDepthInstrumentation(instrumentation.getQueryDepth().getDepth()));
        }

```
Enabling one of the instrumentations above I got a simple NPE:

![image](https://user-images.githubusercontent.com/22281426/97901985-325b8000-1d3d-11eb-887c-6b7dae0257ae.png)

**Comment by aoudiamoncef** [comment]
It seems that variables are empty event if there are defaults values in the query.

**Comment by bbakerman** [comment]
I am able to reproduce this a bug

```
 def sdl = """ 
                type Query { foo : FooType }
                type FooType { bar : String }
                """
        def instrumentation = new ChainedInstrumentation([
                new MaxQueryComplexityInstrumentation(20),
                new MaxQueryDepthInstrumentation(20)
        ])
        def graphQL = TestUtil.graphQL(sdl)
                .instrumentation(instrumentation)
                .build()

        when:
        def er = graphQL.execute('''
            query withDefaults( $var : Boolean = true) {
                foo @include(if: $var) {
                    bar
                }
            }
        ''')

        then:
        er.errors.isEmpty()
```

```

java.lang.NullPointerException
	at graphql.execution.ConditionalNodes.getDirectiveResult(ConditionalNodes.java:39)
	at graphql.execution.ConditionalNodes.shouldInclude(ConditionalNodes.java:24)
	at graphql.analysis.NodeVisitorWithTypeTracking.visitField(NodeVisitorWithTypeTracking.java:173)
	at graphql.language.Field.accept(Field.java:191)
	at graphql.language.NodeTraverser$1.enter(NodeTraverser.java:61)
	at graphql.util.Traverser.traverse(Traverser.java:144)
	at graphql.language.NodeTraverser.doTraverse(NodeTraverser.java:149)
	at graphql.language.NodeTraverser.depthFirst(NodeTraverser.java:69)
	at graphql.analysis.QueryTraverser.visitImpl(QueryTraverser.java:178)
	at graphql.analysis.QueryTraverser.visitPostOrder(QueryTraverser.java:83)
	at graphql.analysis.MaxQueryComplexityInstrumentation.lambda$beginValidation$4(MaxQueryComplexityInstrumentation.java:88)
	at graphql.execution.instrumentation.SimpleInstrumentationContext.onCompleted(SimpleInstrumentationContext.java:48)
	at graphql.execution.instrumentation.ChainedInstrumentation$ChainedInstrumentationContext.lambda$onCompleted$1(ChainedInstrumentation.java:258)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at graphql.execution.instrumentation.ChainedInstrumentation$ChainedInstrumentationContext.onCompleted(ChainedInstrumentation.java:258)
	at graphql.GraphQL.validate(GraphQL.java:588)
	at graphql.GraphQL.parseAndValidate(GraphQL.java:550)
	at graphql.GraphQL.lambda$parseValidateAndExecute$5(GraphQL.java:519)
	at graphql.execution.preparsed.NoOpPreparsedDocumentProvider.getDocument(NoOpPreparsedDocumentProvider.java:15)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:521)
	at graphql.GraphQL.executeAsync(GraphQL.java:490)
	at graphql.GraphQL.execute(GraphQL.java:421)
	at graphql.GraphQL.execute(GraphQL.java:303)
	at graphql.execution.ConditionalNodesTest.can default conditional node values(ConditionalNodesTest.groovy:57)
```

It's caused by ConditionalNodes being invoked BUT the variable coercer has not run yet to default the variables (which happens after parse/validate.

Both of these instrumentions call 

```
        QueryTraverser queryTraverser = QueryTraverser.newQueryTraverser()
                .schema(executionContext.getGraphQLSchema())
                .document(executionContext.getDocument())
                .operationName(executionContext.getOperationDefinition().getName())
                .variables(executionContext.getVariables())
                .build();

```

we have to move the variable coercing code into this so that we can do the defaulting as required

**Comment by bbakerman** [comment]
eg

```
        Map<String, Object> inputVariables = executionInput.getVariables();
        List<VariableDefinition> variableDefinitions = operationDefinition.getVariableDefinitions();

        Map<String, Object> coercedVariables;
        try {
            coercedVariables = valuesResolver.coerceVariableValues(graphQLSchema, variableDefinitions, inputVariables);
        } catch (RuntimeException rte) {
            if (rte instanceof GraphQLError) {
                return completedFuture(new ExecutionResultImpl((GraphQLError) rte));
            }
            throw rte;
        }

```

This type of code.


The work around here is to define the conditional variables explicitly until this bug is fixed when using these instrumentions
