### ISSUE TITLE
AstPrinter throws on empty descriptions

### ISSUE THREAD

**Issue by pcarrier** [graphql-java/graphql-java#2151]
**Describe the bug**

`graphql.language.AstPrinter.description` assumes non-null descriptions are also non-empty through `boolean startNewLine = description.getContent().charAt(0) == '\n';` and throws whenever it encounters an empty description.

**To Reproduce**

```kt
import graphql.language.AstPrinter
import graphql.parser.Parser

fun main() {
    AstPrinter.printAst(Parser().parseDocument("""
        "" scalar Demo
    """))
}
```

```
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at graphql.language.AstPrinter.description(AstPrinter.java:498)
	at graphql.language.AstPrinter.lambda$scalarTypeDefinition$25(AstPrinter.java:323)
	at graphql.language.AstPrinter.node(AstPrinter.java:426)
	at graphql.language.AstPrinter.node(AstPrinter.java:416)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at graphql.language.AstPrinter.join(AstPrinter.java:517)
	at graphql.language.AstPrinter.join(AstPrinter.java:512)
	at graphql.language.AstPrinter.lambda$document$3(AstPrinter.java:88)
	at graphql.language.AstPrinter.printImpl(AstPrinter.java:614)
	at graphql.language.AstPrinter.printAst(AstPrinter.java:594)
	at graphql.language.AstPrinter.printAst(AstPrinter.java:583)
	at DemoKt.main(Demo.kt:5)
	at DemoKt.main(Demo.kt)

Process finished with exit code 1
```

**Comment by andimarek** [comment]
this looks indeed like a bug @pcarrier: would you be able to provide a PR for that? that would be great
