### ISSUE TITLE
no field with name xxxxxx found in object yyyyyyyyy

### ISSUE THREAD

**Issue by roggenbrot** [graphql-java/graphql-java#2163]
When trying to access the fields of selection set (getFields(),  getImmediateFields() ...) of a mutation return value, the following exception is thrown:

```
graphql.AssertException: no field with name create found in object CustomQuery
	at graphql.Assert.assertNotNull(Assert.java:17)
	at graphql.normalized.FieldCollectorNormalizedQuery.collectField(FieldCollectorNormalizedQuery.java:218)
	at graphql.normalized.FieldCollectorNormalizedQuery.collectFields(FieldCollectorNormalizedQuery.java:132)
	at graphql.normalized.FieldCollectorNormalizedQuery.collectFields(FieldCollectorNormalizedQuery.java:86)
	at graphql.normalized.NormalizedQueryTreeFactory.buildFieldWithChildren(NormalizedQueryTreeFactory.java:101)
	at graphql.normalized.NormalizedQueryTreeFactory.buildFieldWithChildren(NormalizedQueryTreeFactory.java:105)
	at graphql.normalized.NormalizedQueryTreeFactory.createNormalizedQueryImpl(NormalizedQueryTreeFactory.java:74)
	at graphql.normalized.NormalizedQueryTreeFactory.createNormalizedQuery(NormalizedQueryTreeFactory.java:32)
	at graphql.execution.ExecutionContext.lambda$getNormalizedQueryTree$0(ExecutionContext.java:207)
	at graphql.util.InterThreadMemoizedSupplier.get(InterThreadMemoizedSupplier.java:31)
	at graphql.execution.ExecutionStrategy.lambda$getNormalizedField$6(ExecutionStrategy.java:296)
	at graphql.schema.DataFetchingFieldSelectionSetImpl.computeValuesLazily(DataFetchingFieldSelectionSetImpl.java:196)
	at graphql.schema.DataFetchingFieldSelectionSetImpl.getImmediateFields(DataFetchingFieldSelectionSetImpl.java:171)
```

This just happens for mutations (and subscriptions), normal queries work without problems.

Root cause seems to be that the root object type in [NormalizedQueryTreeFactory](https://github.com/graphql-java/graphql-java/blob/afaa9aa1f321ef4aed7ef6ccac3e2efdd8413874/src/main/java/graphql/normalized/NormalizedQueryTreeFactory.java#L55) is hardcoded to query types:

```java
CollectFieldResult topLevelFields = fieldCollector.collectFromOperation(parameters, operationDefinition,  graphQLSchema.getQueryType());
```

Setting the root type based on the operation definition solves this problem:

```java
final GraphQLObjectType rootType;
if (operationDefinition.getOperation() == OperationDefinition.Operation.QUERY) {
    rootType = graphQLSchema.getQueryType();
} else if (operationDefinition.getOperation() == OperationDefinition.Operation.MUTATION) {
    rootType = graphQLSchema.getMutationType();
} else if (operationDefinition.getOperation() == OperationDefinition.Operation.SUBSCRIPTION) {
    rootType = graphQLSchema.getSubscriptionType();
} else {
    throw new IllegalStateException("Unknown operation type " + operationDefinition.getOperation());
}

CollectFieldResult topLevelFields = fieldCollector.collectFromOperation(parameters, operationDefinition,  rootType);
```

### Steps to reproduce

1.  Create a mutation type that extends Mutation
```
type CustomMutation extends Mutation{
        create {
               test1: String
               test2: String
        }
}
```

2. Create a dataloader for  "test1"
3. Try to accesss `getImmediateFields` of the selection set

**Comment by dfa1** [comment]
could be the same issue of https://github.com/graphql-java/graphql-java/pull/2126 ?

**Comment by roggenbrot** [comment]
Seems to be the same issue.

Sorry, just searched issues for duplicates

**Comment by roggenbrot** [comment]
Duplicate of #2117
