### ISSUE TITLE
Introspection query broken by GraphQLTypeReference

### ISSUE THREAD

**Issue by pcarrier** [graphql-java/graphql-java#219]
```
import graphql.ExecutionResult;
import graphql.GraphQL;
import graphql.GraphQLError;
import graphql.introspection.IntrospectionQuery;
import graphql.schema.GraphQLObjectType;
import graphql.schema.GraphQLSchema;
import graphql.schema.GraphQLTypeReference;

import static graphql.schema.GraphQLFieldDefinition.newFieldDefinition;
import static graphql.schema.GraphQLObjectType.newObject;

public class Bug {
    public static void main(String... args) {
        final GraphQLObjectType queryType = newObject()
                .name("QueryType")
                .field(newFieldDefinition()
                        .name("self")
                        .type(new GraphQLTypeReference("QueryType"))
                        .build())
                .build();
        final GraphQLSchema schema = GraphQLSchema.newSchema().query(queryType).build();
        final ExecutionResult result = new GraphQL(schema).execute(IntrospectionQuery.INTROSPECTION_QUERY);
        if (result.getErrors() != null && !result.getErrors().isEmpty()) {
            for (GraphQLError error : result.getErrors()) {
                System.err.println(error.getMessage());
            }
        }
    }
}
```

=>

```
Exception in thread "main" graphql.GraphQLException: Cannot return null for non-nullable type: [Field{name='kind', alias='null', arguments=[], directives=[], selectionSet=null}]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:54)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:46)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:88)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:46)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:88)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:52)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:46)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:88)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:52)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:132)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:96)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:61)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:46)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:88)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:52)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:132)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:96)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:61)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:52)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:46)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:88)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:52)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:46)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
	at graphql.execution.Execution.executeOperation(Execution.java:60)
	at graphql.execution.Execution.execute(Execution.java:33)
	at graphql.GraphQL.execute(GraphQL.java:78)
	at graphql.GraphQL.execute(GraphQL.java:55)
	at graphql.GraphQL.execute(GraphQL.java:47)
	at graphql.GraphQL.execute(GraphQL.java:43)
	at apollo.optics.graphql.GraphQLSchemaHandler.<init>(GraphQLSchemaHandler.java:29)
	at apollo.optics.graphql.GraphQLSchemaHandler.main(GraphQLSchemaHandler.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

Process finished with exit code 1
```

**Comment by pcarrier** [comment]
Nevermind, bad repro
