### ISSUE TITLE
schema fails to build for directive argument with recursive argument as input 

### ISSUE THREAD

**Issue by Andy2003** [graphql-java/graphql-java#2238]
**Describe the bug**
Using a recursive input type as argument for an directive will result in the following error when compiling the schema:

```
Internal error: should never happen: cannot build value of type Recursive from object class ObjectValue with instance ObjectValue{objectFields=[ObjectField{name='name', value=StringValue{value='test'}}]}
graphql.AssertException: Internal error: should never happen: cannot build value of type Recursive from object class ObjectValue with instance ObjectValue{objectFields=[ObjectField{name='name', value=StringValue{value='test'}}]}
	at graphql.Assert.assertShouldNeverHappen(Assert.java:53)
	at graphql.schema.idl.SchemaGeneratorHelper.buildValue(SchemaGeneratorHelper.java:282)
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildObjectValue$1(SchemaGeneratorHelper.java:303)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
	at graphql.schema.idl.SchemaGeneratorHelper.buildObjectValue(SchemaGeneratorHelper.java:300)
	at graphql.schema.idl.SchemaGeneratorHelper.buildValue(SchemaGeneratorHelper.java:280)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectiveArgument(SchemaGeneratorHelper.java:403)
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildDirective$9(SchemaGeneratorHelper.java:384)
	at graphql.collect.ImmutableKit.map(ImmutableKit.java:83)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirective(SchemaGeneratorHelper.java:384)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirective(SchemaGeneratorHelper.java:355)
	at graphql.schema.idl.SchemaGeneratorHelper.buildDirectives(SchemaGeneratorHelper.java:731)
	at graphql.schema.idl.SchemaGeneratorHelper.buildObjectType(SchemaGeneratorHelper.java:825)
	at graphql.schema.idl.SchemaGeneratorHelper.buildOutputType(SchemaGeneratorHelper.java:953)
	at graphql.schema.idl.SchemaGeneratorHelper.lambda$buildAdditionalTypes$46(SchemaGeneratorHelper.java:1181)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:485)
	at graphql.schema.idl.SchemaGeneratorHelper.buildAdditionalTypes(SchemaGeneratorHelper.java:1171)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchemaImpl(SchemaGenerator.java:111)
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:96)
```

**To Reproduce**

Compile following schema:

```graphql
directive @test(arg: Recursive) on OBJECT
input Recursive {
  deeper: Recursive
  name: String
}
type Test @test(arg: { deeper: {name: "test"}}){
  field: String
}
type Query {
}
```

**Comment by bbakerman** [comment]
Yeah nice catch

**Comment by bbakerman** [comment]
See https://github.com/graphql-java/graphql-java/pull/2422 - this shows it is working on latest master - I am not sure when  this got fixed but it works on master now
