### ISSUE TITLE
Unions in unions cause an NPE

### ISSUE THREAD

**Issue by bbakerman** [graphql-java/graphql-java#2247]
**Describe the bug**
if you add a union inside a union (which is not allowed) you get a NPE in the schema generation

```
Caused by: java.lang.ClassCastException: graphql.schema.GraphQLUnionType cannot be cast to graphql.schema.GraphQLObjectType
	at graphql.schema.idl.SchemaGenerator.lambda$buildUnionType$19(SchemaGenerator.java:629)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at graphql.schema.idl.SchemaGenerator.buildUnionType(SchemaGenerator.java:624)
	at graphql.schema.idl.SchemaGenerator.buildOutputType(SchemaGenerator.java:438)
	at graphql.schema.idl.SchemaGenerator.buildField(SchemaGenerator.java:784)
	at graphql.schema.idl.SchemaGenerator.lambda$buildObjectType$5(SchemaGenerator.java:501)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
```

I suspect the pre-validation is not strong enough in this area

**To Reproduce**

```
union FooUnion = type1 | typ2
union BarUnion = FooUnion | type3
```

and run that through schema gen.

**Comment by dondonz** [comment]
I tried to re-create the issue, and it seems this NPE has been fixed in the meantime.

My test:
```
def "union of union invalid - schema only"() {
    def spec = '''
    	type Query {
            getPet : Pet
        }
            
        type Dog {
            collar : String
        }
            
        type Tiger {
            hungry : Boolean
        }
            
        type HouseCat {
            name : String
        }
            
        union Pet = Dog | Cat
            
        union Cat = Tiger | HouseCat
    '''
        
    def reader = new StringReader(spec)
    def registry = new SchemaParser().parse(reader)
    def options = SchemaGenerator.Options.defaultOptions()

    when:
    // This is not creating a NPE - this is raising an error as expected
    def npeSchema = new SchemaGenerator().makeExecutableSchema(options, registry, TestUtil.mockRuntimeWiring)
}
```

Which generates the correct error:
```
errors=[The member types of a Union type must all be Object base types. member type 'Cat' in Union 'Pet' is invalid.]
SchemaProblem{errors=[The member types of a Union type must all be Object base types. member type 'Cat' in Union 'Pet' is invalid.]}
```

**Comment by bbakerman** [comment]
Thanks for looking into this
