### ISSUE TITLE
graphql.relay.Base64#fromBase64 throws ArrayIndexOutOfBoundsException on unicode string

### ISSUE THREAD

**Issue by Jimexist** [graphql-java/graphql-java#251]
```
Base64.fromBase64("🏃")
```

when the input is an invalid unicode, the error will be:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 57283
	at javax.xml.bind.DatatypeConverterImpl.guessLength(DatatypeConverterImpl.java:659)
	at javax.xml.bind.DatatypeConverterImpl._parseBase64Binary(DatatypeConverterImpl.java:692)
	at javax.xml.bind.DatatypeConverterImpl.parseBase64Binary(DatatypeConverterImpl.java:434)
	at javax.xml.bind.DatatypeConverter.parseBase64Binary(DatatypeConverter.java:342)
	at graphql.relay.Base64.fromBase64(Base64.java:26)
```

**Comment by dminkovsky** [comment]
Hi @Jimexist,

Thanks for posting this. I wonder, maybe the client should be catching these exceptions?

**Comment by Jimexist** [comment]
the client is seeing this (our set up is jersey and dropwizard based, and this is printed on log and client gets 400 as configured).

**Comment by Jimexist** [comment]
ideally this can be solved using java 8's Base64 class but i guess the back-compat dependency requirement forbids that

**Comment by Jimexist** [comment]
this is arguably a bug in `javax.xml.bind.DatatypeConverterImpl.guessLength` presuming that a char must fit into a byte - which is not the case in unicode. i think at least the excetion thrown out should not be array index out of bound which is misleading

**Comment by andimarek** [comment]
@Jimexist Is this solved with https://github.com/graphql-java/graphql-java/pull/361 ?

**Comment by Jimexist** [comment]
@andimarek yes i think so
