### ISSUE TITLE
eliminate the need to register typeResolver for every interface and union

### ISSUE THREAD

**Issue by eduarddrenth** [graphql-java/graphql-java#2639]
**Is your feature request related to a problem? Please describe.**

For every interface and union in the schema a line like this is needed (hard and time consuming to find):
```
                .type(PagingInterface.class.getSimpleName(), tw -> tw.typeResolver(graphQLSchemaBuilder.getTypeResolver()))
```
where the type resolver is like this:

```
            typeResolver = new TypeResolver() {
                @Override
                public GraphQLObjectType getType(TypeResolutionEnvironment env) {
                    Object o = env.getObject();
                    return env.getSchema().getObjectType(o.getClass().getSimpleName());
                }
            };
```

**Describe the solution you'd like**

Perhaps a generic TypeResolver like above can be registered by default for interfaces and unions?

**Comment by jord1e** [comment]
You can do so yourself by adding a WiringFactory whilst building your RuntimeWiring:

```java
public class Issue2639 {

    private record T1(String a) {
    }

    private record T2(String b) {
    }

    private record T3(String c) {
    }

    static class DefaultInterfaceAndUnionWiringFactory implements WiringFactory {
        @Override
        public boolean providesTypeResolver(InterfaceWiringEnvironment environment) {
            return true;
        }

        @Override
        public TypeResolver getTypeResolver(InterfaceWiringEnvironment environment) {
            return new ClassNameTypeResolver();
        }

        @Override
        public boolean providesTypeResolver(UnionWiringEnvironment environment) {
            return true;
        }

        @Override
        public TypeResolver getTypeResolver(UnionWiringEnvironment environment) {
            return new ClassNameTypeResolver();
        }

        private static class ClassNameTypeResolver implements TypeResolver {
            @Override
            public GraphQLObjectType getType(TypeResolutionEnvironment env) {
                String targetTypeName = env.getObject().getClass().getSimpleName();
                GraphQLType schemaType = env.getSchema().getType(targetTypeName);
                if (!(schemaType instanceof GraphQLObjectType)) {
                    // Implicit null check because of instanceof
                    throw new RuntimeException("Default TypeResolver could not find matching GraphQLObjectType type for Java object of type "
                            + targetTypeName + " (was: " + schemaType + ")");
                }
                return (GraphQLObjectType) schemaType;
            }
        }
    }


    public static void main(String[] args) {
        System.out.println("---");
        final String schema = """
                type Query {
                  unionTest1: TestUnion
                  unionTest2: TestUnion
                  unionTest3: TestUnion
                }
                                
                type T1 {
                  a: String
                }
                                
                type T2 {
                  b: String
                }
                                
                union TestUnion = T1 | T2
                """;

        TypeDefinitionRegistry registry = new SchemaParser()
                .parse(schema);

        RuntimeWiring runtimeWiring = RuntimeWiring
                .newRuntimeWiring()
                .type("Query", builder -> builder
                        .dataFetcher("unionTest1", environment -> new T1("testResult1"))
                        .dataFetcher("unionTest2", environment -> new T2("testResult2"))
                        .dataFetcher("unionTest3", environment -> new T3("testResult3"))
                )
                .wiringFactory(new CombinedWiringFactory(List.of(new DefaultInterfaceAndUnionWiringFactory())))
                .build();

        GraphQLSchema graphQLSchema = new SchemaGenerator()
                .makeExecutableSchema(registry, runtimeWiring);

        GraphQL graphQL = GraphQL
                .newGraphQL(graphQLSchema)
                .build();

        Map<String, Object> data = graphQL
                .execute(ExecutionInput
                        .newExecutionInput()
                        .query("""
                                query ($includeT3: Boolean!) {
                                  unionTest1 {
                                    ...UnionTestFragment
                                  }
                                  unionTest2 {
                                    ...UnionTestFragment
                                  }
                                  unionTest3 @include(if: $includeT3) {
                                    ...UnionTestFragment
                                  }
                                }
                                                                
                                fragment UnionTestFragment on TestUnion {
                                  ...on T1 {
                                    a
                                  }
                                  ...on T2 {
                                    b
                                  }
                                }
                                """)

                        .variables(Map.of("includeT3", false))
                        .build()
                )
                .toSpecification();

        System.out.println(data);
        System.out.println("---");
    }
```

When `includeT3` is set to `false` the output is:
```
---
{data={unionTest1={a=testResult1}, unionTest2={b=testResult2}}}
---
```
when it is set to `true` the output is:
```
[main] ERROR notprivacysafe.graphql.GraphQL - Execution '6420d5a0-f70c-4ff7-94d9-5dfeebb8b61d' threw exception when executing : query : 'query ($includeT3: Boolean!) {
  unionTest1 {
    ...UnionTestFragment
  }
  unionTest2 {
    ...UnionTestFragment
  }
  unionTest3 @include(if: $includeT3) {
    ...UnionTestFragment
  }
}

fragment UnionTestFragment on TestUnion {
  ...on T1 {
    a
  }
  ...on T2 {
    b
  }
}
'. variables 'graphql.collect.ImmutableMapWithNullValues@a6c6d1c8'
java.util.concurrent.CompletionException: java.lang.RuntimeException: Default TypeResolver could not find matching GraphQLObjectType type for Java object of type T3 (was: null)
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
	<snipped>
	at graphql.GraphQL.execute(GraphQL.java:433)
	at Issue2639.main(Issue2639.java:109)
Caused by: java.lang.RuntimeException: Default TypeResolver could not find matching GraphQLObjectType type for Java object of type T3 (was: null)
Caused by: java.lang.RuntimeException: Default TypeResolver could not find matching GraphQLObjectType type for Java object of type T3 (was: null)

	at Issue2639$DefaultInterfaceAndUnionWiringFactory$ClassNameTypeResolver.getType(Issue2639.java:59)
	at graphql.execution.ResolveType.resolveTypeForUnion(ResolveType.java:67)
	<snipped>
	at graphql.execution.Execution.executeOperation(Execution.java:159)
	... 6 more
Exception in thread "main" java.lang.RuntimeException: Default TypeResolver could not find matching GraphQLObjectType type for Java object of type T3 (was: null)
	at Issue2639$DefaultInterfaceAndUnionWiringFactory$ClassNameTypeResolver.getType(Issue2639.java:59)
	<snipped>
	at graphql.GraphQL.execute(GraphQL.java:433)
	at Issue2639.main(Issue2639.java:109)
```

**Comment by eduarddrenth** [comment]
thanks, the factory solution looks nice

**Comment by eduarddrenth** [comment]
Using this now (static finals more efficient, possible because threadsafe):

```java
public class GraphqlSimpleWiring implements WiringFactory {

    private static final TypeResolver TYPE_RESOLVER = new TypeResolver() {
        @Override
        public GraphQLObjectType getType(TypeResolutionEnvironment env) {
            String targetTypeName = env.getObject().getClass().getSimpleName();
            GraphQLType schemaType = env.getSchema().getType(targetTypeName);
            if (!(schemaType instanceof GraphQLObjectType)) {
                throw new RuntimeException(
                        String.format("schemaType %s (found for Java type %s) is not a GraphQLObjectType",schemaType,targetTypeName));
            }
            return (GraphQLObjectType) schemaType;        }
    };

    @Override
    public boolean providesTypeResolver(InterfaceWiringEnvironment environment) {
        return true;
    }

    @Override
    public TypeResolver getTypeResolver(Interf:aceWiringEnvironment environment) {
        return TYPE_RESOLVER;
    }

    @Override
    public boolean providesTypeResolver(UnionWiringEnvironment environment) {
        return true;
    }

    @Override
    public TypeResolver getTypeResolver(UnionWiringEnvironment environment) {
        return TYPE_RESOLVER;
    }

    public static final GraphqlSimpleWiring GRAPHQL_SIMPLE_WIRING = new GraphqlSimpleWiring();
}
```

**Comment by jord1e** [comment]
Please note that the TypeResolver is only created **once** (for each union and interface in this case) whilst **creating** the schema. The TypeResolver is not created every request. I would argue that using an anonymous class is counter productive in this case. Especially when debugging or profiling, a named class would be clearer.

The [getType()](https://github.com/graphql-java/graphql-java/blob/03c61693770328edf14353de75350be650702167/src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java#L455) method [accesses a LinkedHashMap](https://github.com/graphql-java/graphql-java/blob/03c61693770328edf14353de75350be650702167/src/main/java/graphql/schema/idl/TypeDefinitionRegistry.java#L61). The [docs for LinkedHashMap](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedHashMap.html) state:
> Note that this implementation is not synchronized. If multiple threads access a linked hash map concurrently, **and at least one of the threads modifies the map structurally**, it must be synchronized externally. This is typically accomplished by synchronizing on some object that naturally encapsulates the map.

The bolded part is especially important, the maps are created at object (TypeDefinitonRegistry) creation time, and never modified after (graphql-java is immutable almost everywhere).

This means that in this case thread safety is not an issue.


https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java#L734-L738

https://github.com/graphql-java/graphql-java/blob/master/src/main/java/graphql/schema/idl/SchemaGeneratorHelper.java#L600-L621

![afbeelding](https://user-images.githubusercontent.com/30464310/146522264-22b2f854-c4f7-4fcb-9782-1aa73ac5b0fa.png)

**Comment by eduarddrenth** [comment]
Thanks, in my specific situation there is no problem, but I'll use a named class, I agree that's clearer
