### ISSUE TITLE
Instant serializing impropertly

### ISSUE THREAD

**Issue by xenoterracide** [graphql-java/graphql-java#2987]
**Describe the bug**

```
2022-10-14 22:48:54.267  WARN 86607 --- [nPool-worker-10] n.g.e.ExecutionStrategy                  : Can't serialize value (/exceptionsConnection/edges[0]/node/createdOn) : Unable to turn TemporalAccessor into full date because of : 'Unsupported field: YearOfEra'.

graphql.schema.CoercingSerializeException: Unable to turn TemporalAccessor into full date because of : 'Unsupported field: YearOfEra'.
	at graphql.scalars.datetime.DateScalar$1.serialize(DateScalar.java:51) ~[graphql-java-extended-scalars-18.1.jar:?]
	at graphql.scalars.datetime.DateScalar$1.serialize(DateScalar.java:34) ~[graphql-java-extended-scalars-18.1.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForScalar(ExecutionStrategy.java:590) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:441) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:404) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:212) ~[graphql-java-18.3.jar:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:211) ~[graphql-java-18.3.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:667) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:454) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:404) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:212) ~[graphql-java-18.3.jar:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:211) ~[graphql-java-18.3.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:667) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:454) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:546) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:500) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:439) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:404) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:212) ~[graphql-java-18.3.jar:?]
	at java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684) ~[?:?]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662) ~[?:?]
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168) ~[?:?]
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:211) ~[graphql-java-18.3.jar:?]
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:60) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValueForObject(ExecutionStrategy.java:667) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:454) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:404) ~[graphql-java-18.3.jar:?]
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:212) ~[graphql-java-18.3.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
	at org.dataloader.DataLoaderHelper.lambda$dispatchQueueBatch$2(DataLoaderHelper.java:252) ~[java-dataloader-3.1.2.jar:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run$$$capture(CompletableFuture.java:1773) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
```

**To Reproduce**

Serialize an `Instant` (I presume, using Netflix DGS)

Java 8, using 18.1 (3?)

**Comment by dondonz** [comment]
Can you provide an example of the code that caused this problem?

**Comment by xenoterracide** [comment]
I probably could... But a quick Google simply shows that the problem is caused by attempting to serialize an instant with a date time for matter without specifying a zone

**Comment by dondonz** [comment]
Thanks, in that case I'll close the issue

**Comment by xenoterracide** [comment]
So you're not interested in being able to serialize an instant then. Okay, w/e

**Comment by andimarek** [comment]
@xenoterracide your comment indicated that you understood the problem. If you think the current behavior is not correct or could be improved, please open an Issue in https://github.com/graphql-java/graphql-java-extended-scalars where the `DateTime` Scalar is maintained.

**Comment by xenoterracide** [comment]
Thanks, sorry I couldn't find that repo earlier
