### ISSUE TITLE
SchemaPrinter cannot print union containing GraphQLTypeReference

### ISSUE THREAD

**Issue by twinprime** [graphql-java/graphql-java#3434]
**Describe the bug**
SchemaPrinter cannot print union containing GraphQLTypeReference

**To Reproduce**
```
val schema = GraphQLUnionType.newUnionType().name("Shape")
                .possibleType(GraphQLTypeReference.typeRef("Circle"))
                .possibleType(GraphQLTypeReference.typeRef("Square"))
                .build()
val printer = SchemaPrinter()
printer.print(schema)

```
The above code (in Kotlin) results in ClassCastException:

```
Exception in thread "main" java.lang.ClassCastException: class graphql.schema.GraphQLTypeReference cannot be cast to class graphql.schema.GraphQLUnmodifiedType (graphql.schema.GraphQLTypeReference and graphql.schema.GraphQLUnmodifiedType are in unnamed module of loader 'app')
	at graphql.schema.GraphQLTypeUtil.unwrapAll(GraphQLTypeUtil.java:199)
	at graphql.schema.DefaultGraphqlTypeComparatorRegistry.unwrapElement(DefaultGraphqlTypeComparatorRegistry.java:54)
	at graphql.schema.DefaultGraphqlTypeComparatorRegistry.lambda$sensibleGroupedOrder$0(DefaultGraphqlTypeComparatorRegistry.java:40)
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.base/java.util.TimSort.sort(TimSort.java:220)
	at java.base/java.util.Arrays.sort(Arrays.java:1307)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at graphql.schema.idl.SchemaPrinter.lambda$unionPrinter$6(SchemaPrinter.java:626)
	at graphql.schema.idl.SchemaPrinter.printSchemaElement(SchemaPrinter.java:1079)
	at graphql.schema.idl.SchemaPrinter.print(SchemaPrinter.java:1052)
	at aero.airlab.common.ktable.support.TestSchemaKt.main(TestSchema.kt:36)
	at aero.airlab.common.ktable.support.TestSchemaKt.main(TestSchema.kt)

```

This means we cannot define a union with recursive reference.

**Comment by bhabegger** [comment]
Ok, the problem is that the comparator internally, uses unwrapAll method which expects as output a GraphQLUnmodifiedType but takes as input any GraphQLType

As GraphQLTypeReference is a GraphQLType, it's an acceptable input, but as it has nothing to unwrap, trying to return itself fails. Here, the proper fix would likely be to change the signature of unwrapAll to only take types extending GraphQLUnmodifiedType as input. 

But this might break existing usages of  the method.

**Comment by bhabegger** [comment]
Have a branch ready... But am not authorized to push a branch.

**Comment by bbakerman** [comment]
> Have a branch ready... But am not authorized to push a branch :(

The model in github is to use Forks - you create a branch in your own clone of the repo and then when you create a PR you reference your clone and not this one

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

ps.  We appreciate all help - thank you

**Comment by bhabegger** [comment]
PR is here : https://github.com/graphql-java/graphql-java/pull/3506 (in case you didn't see yet)

**Comment by bbakerman** [comment]
I am happy to accep the fix here but really its not a situation we get if we build a schemas proper

When we build a full GraphQLSchema - then all type references get replaced with actual references because we have them all.

So this bug turns up in the example above (an incomplete type) but it would never turn up on a type from a complete schema
