### ISSUE TITLE
A weird graphql.AssertException is thrown at a place where it does not make sense.

### ISSUE THREAD

**Issue by TsvetomirValchev** [graphql-java/graphql-java#3477]
**Describe the bug**

Previously we could execute a query like:

```
query quests {
  quests(
    filter: {
      states: ["ONGOING"]
    }
  ) {
    questId
  }
}
```

and it would return a list of all concrete Quest/Questline objects that inherit the Quest interface ( i.e. a list that has EpicQuestline and SpecificQuest in the example schema ).

Now whenever there is an existing entry that is child of Questline in the database in the specific state that you query for, an error is thrown ( so let's say there is an entry in the database for EpicQuestline that has status ONGOING, if you query for status: ONGOING ) , it would throw an error:

```
graphql.AssertException: You have asked for named object type 'Questline' but it's not an object type but rather a 'graphql.schema.GraphQLInterfaceType'
	at graphql.Assert.assertTrue(Assert.java:78)
	at graphql.schema.GraphQLSchema.getObjectType(GraphQLSchema.java:295)
	at graphql.kickstart.tools.DictionaryTypeResolver.getType(DictionaryTypeResolver.kt:27)
	at graphql.execution.ResolveType.resolveAbstractType(ResolveType.java:62)
	at graphql.execution.ResolveType.resolveTypeForInterface(ResolveType.java:53)
	at graphql.execution.ResolveType.resolveType(ResolveType.java:39)
	at graphql.execution.ExecutionStrategy.resolveType(ExecutionStrategy.java:720)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:483)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:586)
	at graphql.execution.ExecutionStrategy.completeValueForList(ExecutionStrategy.java:543)
	at graphql.execution.ExecutionStrategy.completeValue(ExecutionStrategy.java:469)
	at graphql.execution.ExecutionStrategy.completeField(ExecutionStrategy.java:435)
	at graphql.execution.ExecutionStrategy.lambda$resolveFieldWithInfo$1(ExecutionStrategy.java:215)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:684)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:662)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2168)
	at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:214)
	at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:55)
	at graphql.execution.Execution.executeOperation(Execution.java:161)
	... 126 common frames omitted

```
**To Reproduce**

Have a schema like this:

[here](https://github.com/TsvetomirValchev/graphql-reproduce/blob/main/service/src/main/resources/schema.graphqls)

A resolver function similar to the one in production for the query that is problematic can be seen:

[here](https://github.com/TsvetomirValchev/graphql-reproduce/blob/main/service/src/main/java/org/example/service/graphql/resolver/GraphqlResolver.java)

The repo provided above is not enough to completely reproduce the issue. It has the dependencies I thought were relevant used in the actual project where the issue was encountered. 

Note:

The project made for reproduction uses example names and implementations of certain methods so if you need anything more specific please let me know. That being said the methods in the resolver where example values are used should not be the problem since it did work as expected for a long time and now has become an issue again.

A colleague of mine mentioned that this issue seems familiar to him and last time something like this was encountered the solution was somewhere in the dependency versions of hibernate-orm plugin and graphql-enhance plugin ( they were incompatible and once the versions were matched the issue was fixed.) This is currently not the case since i checked the versions of the aforementioned dependencies and it seems the issue is coming from somewhere else.

Please let me know if there is anything else you need to know and I will be sure to provide the information ASAP. This is my first time writing an issue like this so please excuse any negligence.

**Comment by andimarek** [comment]
Hi ... the code causing the exception is in ```	at graphql.kickstart.tools.DictionaryTypeResolver.getType(DictionaryTypeResolver.kt:27)
```
is another project (https://github.com/graphql-java-kickstart) not directly GraphQL Java. I would recommend to reach out to them.

**Comment by TsvetomirValchev** [comment]
Yes, thank you and sorry the trouble!
