### ISSUE TITLE
graphql.validation.ValidationContext#getFragment could return NULL, resulting NPE

### ISSUE THREAD

**Issue by Jimexist** [graphql-java/graphql-java#355]
```
ERROR [2017-04-04 06:17:33,280] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 18f3edc8feafb541
! java.lang.NullPointerException: null
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:33)
! at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:26)
! at graphql.validation.RulesVisitor.checkFragmentSpread(RulesVisitor.java:116)
! at graphql.validation.RulesVisitor.enter(RulesVisitor.java:57)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:31)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
! at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:26)
! at graphql.validation.Validator.validateDocument(Validator.java:20)
! at graphql.GraphQL.execute(GraphQL.java:79)
```

**Comment by bbakerman** [comment]
Can you please leave more evidence on how this issue can be reproduced.

A query for example would help a lot

**Comment by bbakerman** [comment]
Ahh yeah I have hit this.  Nodes can have null children.  (Should have returned empty list but here we are)

I think a recent PR fixed this

**Comment by corydolphin** [comment]
https://github.com/graphql-java/graphql-java/pull/391 should've fixed this
