### ISSUE TITLE
graphql.execution.ExecutionContextBuilder#build could throw, instead of returning GraphQlError

### ISSUE THREAD

**Issue by Jimexist** [graphql-java/graphql-java#356]
```
ERROR [2017-04-03 17:10:27,145] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 78f32c237eb61e22
! graphql.GraphQLException: Null value for NonNull type GraphQLNonNull{wrappedType=GraphQLScalarType{name='String', description='Built-in String', coercing=graphql.Scalars$4@8fc8018}}
! at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:70)
! at graphql.execution.ValuesResolver.coerceValueForInputObjectType(ValuesResolver.java:94)
! at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:84)
! at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:68)
! at graphql.execution.ValuesResolver.coerceValueForInputObjectType(ValuesResolver.java:94)
! at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:84)
! at graphql.execution.ValuesResolver.coerceValue(ValuesResolver.java:68)
! at graphql.execution.ValuesResolver.getVariableValue(ValuesResolver.java:59)
! at graphql.execution.ValuesResolver.getVariableValues(ValuesResolver.java:16)
! at graphql.execution.ExecutionContextBuilder.build(ExecutionContextBuilder.java:48)
! at graphql.execution.Execution.execute(Execution.java:30)
! at graphql.GraphQL.execute(GraphQL.java:84)

```

**Comment by Jimexist** [comment]
i think it is confusing that execution could at the same time throw `GraphQlError` and return `GraphQlError`

**Comment by bbakerman** [comment]
yeah there is a fix for this.  Its contained via PRs that address #268

**Comment by bbakerman** [comment]
I am going to close this one as a duplicate and hence use #268 as the canonical issue
