### ISSUE TITLE
Guava shading issue with signer information

### ISSUE THREAD

**Issue by karlhenselin** [graphql-java/graphql-java#3724]
**Describe the bug**
I receive the error
java.lang.SecurityException: class "com.google.common.collect.Streams"'s signer information does not match signer information of other classes in the same package
When I have a war file with pac4j-core-5.7.3.jar, guava 33.0 and graphql-java 20.9 in it.
When I try to login to tomcat with SSO I get the stacktrace
```
java.lang.SecurityException: class "com.google.common.collect.Streams"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2337)
	at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:810)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1293)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1141)
	at org.pac4j.core.profile.BasicUserProfile.mergeCollectionAttributes(BasicUserProfile.java:144)
	at org.pac4j.core.profile.BasicUserProfile.getValueForMap(BasicUserProfile.java:130)
	at org.pac4j.core.profile.BasicUserProfile.addAttributeToMap(BasicUserProfile.java:117)
	at org.pac4j.core.profile.BasicUserProfile.addAttribute(BasicUserProfile.java:156)
	at org.pac4j.core.profile.definition.ProfileDefinition.convertAndAdd(ProfileDefinition.java:75)
	at org.pac4j.saml.credentials.authenticator.SAML2Authenticator.validate(SAML2Authenticator.java:106)
	at org.pac4j.saml.credentials.authenticator.SAML2Authenticator.validate(SAML2Authenticator.java:25)
	at org.pac4j.core.client.BaseClient.lambda$retrieveCredentials$0(BaseClient.java:70)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.pac4j.core.client.BaseClient.retrieveCredentials(BaseClient.java:67)
``` 

I understand that you shaded guava. Can you instead shade it with a different package name so that this won't happen?
- This doesn't make sense though, as when I opened the 20.9 jar, it was already in another package, so it shouldn't be possible.

**To Reproduce**
It is tricky to reproduce. You wouldn't get it every time. Only some of our customers seem to be affected.

**Comment by dondonz** [comment]
Thanks for closing out the issue
