### ISSUE TITLE
ClassCastException: graphql.schema.GraphQLObjectType cannot be cast to graphql.schema.GraphQLInputType

### ISSUE THREAD

**Issue by opshubdata** [graphql-java/graphql-java#373]
We are using same schema for Query and Mutation. While generation of schema it gives below error,

```
Exception in thread "main" java.lang.ClassCastException: graphql.schema.GraphQLObjectType cannot be cast to graphql.schema.GraphQLInputType
	at graphql.schema.GraphQLArgument.replaceTypeReferences(GraphQLArgument.java:30)
	at graphql.schema.SchemaUtil.resolveTypeReferencesForFieldsContainer(SchemaUtil.java:153)
	at graphql.schema.SchemaUtil.replaceTypeReferences(SchemaUtil.java:141)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:110)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:104)
	at com.opshub.oim.graphql.common.GraphQLConstants.main(GraphQLConstants.java:107)
```

Here is the main program to reproduce the issue,
```

public static void main(final String[] args) {
		final GraphQLInputObjectType attributeListInputObjectType = GraphQLInputObjectType.newInputObject().name("attributes")
				.description("attribute")
				.field(GraphQLInputObjectField.newInputObjectField().type(GraphQLString).name("key").build())
				.field(GraphQLInputObjectField.newInputObjectField().type(GraphQLString).name("value").build()).build();

		final GraphQLObjectType attributeListObjectType = GraphQLObjectType.newObject().name("attributes").description("attribute")
				.field(newFieldDefinition().type(GraphQLString).name("key").build())
				.field(newFieldDefinition().type(GraphQLString).name("value").build()).build();

		final GraphQLObjectType systemForMutation = GraphQLObjectType.newObject().name("systems").description("systems")
				.field(newFieldDefinition().name("attributes").type(new GraphQLList(attributeListInputObjectType)).build())
				.field(newFieldDefinition().name("attributes1").type(attributeListObjectType).build())
				.field(newFieldDefinition().type(new GraphQLTypeReference("systems")).name("parentSystem").build())
				.build();

		final GraphQLObjectType systemForQuery = GraphQLObjectType.newObject().name("systems").description("systems")
				.field(newFieldDefinition().name("attributes").type(new GraphQLList(attributeListObjectType)).build())
				.field(newFieldDefinition().name("attributes1").type(attributeListObjectType).build())
				.field(newFieldDefinition().type(new GraphQLTypeReference("systems")).name("parentSystem").build())
				.build();

		final GraphQLFieldDefinition systemWithArgsForMutation = newFieldDefinition().name("systems").type(systemForMutation)
				.dataFetcher(new SystemDataFetcher())
				.argument(GraphQLArgument.newArgument().name("attributes").type(new GraphQLList(attributeListInputObjectType)).build())
				.argument(GraphQLArgument.newArgument().name("attributes1").type(attributeListInputObjectType).build()).build();

		final GraphQLFieldDefinition systemWithArgsForQuery = newFieldDefinition().name("systems").type(systemForQuery)
				.dataFetcher(new SystemDataFetcher())
				.argument(GraphQLArgument.newArgument().name("attributes").type(new GraphQLList(attributeListObjectType)).build())
				.argument(GraphQLArgument.newArgument().name("attributes1").type(attributeListInputObjectType).build()).build();
		final GraphQLObjectType queryType = GraphQLObjectType.newObject().name("query").field(systemWithArgsForQuery).build();
		final GraphQLObjectType mutation = GraphQLObjectType.newObject().name("mutation").field(systemWithArgsForMutation).build();

		final GraphQLSchema schema = GraphQLSchema.newSchema().query(queryType).mutation(mutation).build();

}
```

Looks like, GraphQL use internal schema caching for resolveTypeReference method.

I think, If we change SchemaUtil.java below line or condition with and then it should work,
```

 GraphQLType resolveTypeReference(GraphQLType type, Map<String, GraphQLType> typeMap)
	/*     */ {
		/* 165 */ if ((type instanceof GraphQLTypeReference) **||** (typeMap.containsKey(type.getName()))) {
```
Regards,
OpsHub Inc.

**Comment by bbakerman** [comment]
You problem is here

             final GraphQLFieldDefinition systemWithArgsForQuery = newFieldDefinition().name("systems").type(systemForQuery)
                .dataFetcher(new SystemDataFetcher())
                .argument(GraphQLArgument.newArgument().name("attributes").type(new GraphQLList(attributeListObjectType)).build())
                .argument(GraphQLArgument.newArgument().name("attributes1").type(attributeListInputObjectType).build()).build();


GraphQLArgument takes InputObjects.  So 

      .type(new GraphQLList(attributeListObjectType)

**Comment by bbakerman** [comment]
The problem is here
                    .argument(GraphQLArgument.newArgument().name("attributes").type(new GraphQLList(attributeListObjectType)).build())

`GraphQLArgument` types MUST be input types.  However you have defined `attributeListObjectType` as

            final GraphQLObjectType attributeListObjectType = GraphQLObjectType.newObject().name("attributes").description("attribute")
                .field(newFieldDefinition().type(GraphQLString).name("key").build())
                .field(newFieldDefinition().type(GraphQLString).name("value").build()).build();

which is clearly an output type.

Also you have confused the system some what by having 2 types named with the same name. 

     GraphQLInputObjectType.newInputObject().name("attributes")...
     GraphQLObjectType.newObject().name("attributes")...

The spec say

http://facebook.github.io/graphql/#sec-Type-System

All types within a GraphQL schema must have unique names. No two provided types may have the same name. No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).

So this is an invalid set of types.

**Comment by bbakerman** [comment]
I hope this helps

**Comment by opshubdata** [comment]
Ah. This error occurred while preparing building schema of nested objects not for list type.  Let me remove unnecessary fields from this example,

```
final GraphQLObjectType attributesObjectType = GraphQLObjectType.newObject().name("attributes1")
				.field(newFieldDefinition().type(GraphQLString).name("key").build())
				.field(newFieldDefinition().type(GraphQLString).name("value").build()).build();

		final GraphQLObjectType systemObjectType = GraphQLObjectType.newObject().name("systems")
				.field(newFieldDefinition().name("attributes1").type(attributesObjectType).build())
				.build();

		final GraphQLInputObjectType attributeInputObjectType = GraphQLInputObjectType.newInputObject()
				.name("attributes1")
				.field(GraphQLInputObjectField.newInputObjectField().type(GraphQLString).name("key").build())
				.field(GraphQLInputObjectField.newInputObjectField().type(GraphQLString).name("value").build()).build();

		final GraphQLFieldDefinition systemWithArgs = newFieldDefinition().name("systems").type(systemObjectType)
				.dataFetcher(new SystemDataFetcher())
				.argument(GraphQLArgument.newArgument().name("attributes1").type(attributeInputObjectType).build()).build();

		final GraphQLObjectType queryType = GraphQLObjectType.newObject().name("query").field(systemWithArgs).build();
		final GraphQLObjectType mutation = GraphQLObjectType.newObject().name("mutation").field(systemWithArgs)
				.build();

		final GraphQLSchema schema = GraphQLSchema.newSchema().query(queryType).mutation(mutation).build();

		String query = "mutation{systems(attributes1:{key:\"1\",value:\"2\"}){attributes1:{key,value}}}";
```

So here, we are using GraphQLInputObjectType object for argument type. But the error is still same.

Let us know if you need any other details or if we are making any mistake to build schema.

**Comment by andimarek** [comment]
@opshubdata As @bbakerman mentioned you can't have to types with the same name: but you used `attributes1` two times. We will improve the error message, but this will not fix your problem: you have to use unique type names.

**Comment by danielocampo2** [comment]
@andimarek but does this limitation applies to any object in your schema? If we have 2 different queries with a parameter, say, "userID" then that means that we can't use that same parameter name even if it represents exactly the same data for both queries?
Thanks!
