### ISSUE TITLE
Facing issue in latest version

### ISSUE THREAD

**Issue by SeenaLibin** [graphql-java/graphql-java#475]
Hi,
When I change from version 2.1.0 to 3.0.0 I am facing the following issue 

```
All types within a GraphQL schema must have unique names. No two provided types may have the same name.
No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).
You have redefined the type 'Authors' from being a 'GraphQLObjectType' to a 'GraphQLObjectType'
	at graphql.schema.SchemaUtil.assertTypeUniqueness(SchemaUtil.java:86)
	at graphql.schema.SchemaUtil.collectTypesForObjects(SchemaUtil.java:122)
	at graphql.schema.SchemaUtil.collectTypes(SchemaUtil.java:56)
	at graphql.schema.SchemaUtil.collectTypes(SchemaUtil.java:48)
	at graphql.schema.SchemaUtil.collectTypesForObjects(SchemaUtil.java:128)
	at graphql.schema.SchemaUtil.collectTypes(SchemaUtil.java:56)
	at graphql.schema.SchemaUtil.collectTypesForObjects(SchemaUtil.java:128)
	at graphql.schema.SchemaUtil.collectTypes(SchemaUtil.java:56)
	at graphql.schema.SchemaUtil.allTypes(SchemaUtil.java:153)
	at graphql.schema.GraphQLSchema.<init>(GraphQLSchema.java:42)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:130)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:125)
```

**Comment by andimarek** [comment]
Hi,

normally this means you have defined the type `Authors` twice: you can only define it once.

**Comment by SeenaLibin** [comment]
Hi,
But the same code worked fine in version 2.1.0

**Comment by oexza** [comment]
that it worked previously is actually a bug. no two types should have
the same name.

**Comment by bbakerman** [comment]
http://facebook.github.io/graphql/#sec-Type-System

> All types within a GraphQL schema must have unique names. No two provided types may have the same name. No provided type may have a name which conflicts with any built in types (including Scalar and Introspection types).

**Comment by andimarek** [comment]
closing it now ... 
@SeenaLibin if you think it is a bug and you don't actually habe two types with the same name, please reopen it again. Thanks!
