### ISSUE TITLE
ClassCastException when when specifying array instead of single value for an enum field in a query/mutation

### ISSUE THREAD

**Issue by danielFesenmeyer** [graphql-java/graphql-java#546]
I get the following exception when setting an array instead of a single value for an enum within a mutation or query:
```
java.lang.ClassCastException: graphql.schema.GraphQLEnumType cannot be cast to graphql.schema.GraphQLNullableType

	at graphql.validation.TraversalContext.getNullableType(TraversalContext.java:181)
	at graphql.validation.TraversalContext.enterImpl(TraversalContext.java:125)
	at graphql.validation.TraversalContext.enter(TraversalContext.java:49)
	at graphql.validation.RulesVisitor.enter(RulesVisitor.java:40)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:31)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34)
	at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:26)
	at graphql.validation.Validator.validateDocument(Validator.java:20)
	at graphql.GraphQL.execute(GraphQL.java:212)
	at graphql.GraphQL.execute(GraphQL.java:187)
	at graphql.GraphQL.execute(GraphQL.java:179)
	at graphql.GraphQL.execute(GraphQL.java:175)
       ...
```

It would be nice to get an appropriate ValidationError (contained in ExecutionResulg.getErrors()) instead.

Can be reproduced with this code:
```
     private GraphQLEnumType enumType = newEnum().name("EnumType").value("Val1").value("Val2").build();

    private GraphQLObjectType queryType = newObject()
            .name("QueryType")
            .field(newFieldDefinition()
                    .name("query")
                    .argument(newArgument().name("fooParam").type(enumType))
                    .type(Scalars.GraphQLInt))
            .build();

    private GraphQLSchema schema = newSchema()
            .query(queryType)
            .build();
    @Test
    public void test() {
        final GraphQL graphQL = newGraphQL(schema).build();
        final ExecutionResult result = graphQL.execute("{query (fooParam: [Val1,Val2])}");
        assertEquals(Collections.emptyList(), result.getErrors());
    }
```

**Comment by andimarek** [comment]
@danielFesenmeyer thank your for reporting and providing a test case!

It will be fixed in the next release: #549
