### ISSUE TITLE
Throw more helpful error when cursor is invalid

### ISSUE THREAD

**Issue by tklovett** [graphql-java/graphql-java#570]
A user attempted to use `listOfThings(after: "04/29/2017") { ... }` as a cursor on a `SimpleListConnection`, which resulted in this low-level exception being thrown to our `DataFetcher`.

```
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
	at java.lang.String.substring(String.java:1931) ~[na:1.8.0_131]
	at graphql.relay.SimpleListConnection.getOffsetFromCursor(SimpleListConnection.java:113) ~[graphql-java-3.0.0.jar:na]
	at graphql.relay.SimpleListConnection.get(SimpleListConnection.java:46) ~[graphql-java-3.0.0.jar:na]
```

```
    private int getOffsetFromCursor(String cursor, int defaultValue) {
        if (cursor == null) {
            return defaultValue;
        }
        String string = new String(getDecoder().decode(cursor), StandardCharsets.UTF_8);
        return Integer.parseInt(string.substring(prefix.length())); <-- thrown here
    }
```
Instead of letting this low-level exception bubble up to callers, it would be nice to catch invalid cursor issues and throw something like `InvalidCursorException` or `IllegalArgumentException("Invalid cursor value: " + cursor)`

**Comment by tklovett** [comment]
A similar low-level exception is thrown when decoding an invalid cursor string on this line:

`String string = new String(getDecoder().decode(cursor), StandardCharsets.UTF_8);`

```
java.lang.IllegalArgumentException: Illegal base64 character 2d
    at java.util.Base64$Decoder.decode0(Base64.java:714)
    at java.util.Base64$Decoder.decode(Base64.java:526)
    at java.util.Base64$Decoder.decode(Base64.java:549)
    at graphql.relay.SimpleListConnection.getOffsetFromCursor(SimpleListConnection.java:112)
    at graphql.relay.SimpleListConnection.get(SimpleListConnection.java:46)
    at com.foo.BarDataFetcher.get(BarDataFetcher.java:35)
```

**Comment by bbakerman** [comment]
Fixed
