### ISSUE TITLE
NullPointerException when fragment used in spread is not defined

### ISSUE THREAD

**Issue by tklovett** [graphql-java/graphql-java#583]
We discovered a `NullPointerException` that can be caused by API callers using a malformed query.

If a query contains a fragment spread for which the fragment is never defined, `NoFragmentCycles` will NPE. Something should probably validate the usage of fragments before this check for fragment cycles.

Some validation appears to happen, so maybe the issue is that the validation doesn't recurse deep enough? Our undefined fragment was nested inside multiple fragment spreads and plain graphql objects.

```
java.lang.NullPointerException: null
    at graphql.validation.rules.NoFragmentCycles.detectCycleRecursive(NoFragmentCycles.java:67) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.rules.NoFragmentCycles.detectCycleRecursive(NoFragmentCycles.java:80) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.rules.NoFragmentCycles.detectCycleRecursive(NoFragmentCycles.java:80) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.rules.NoFragmentCycles.detectCycleRecursive(NoFragmentCycles.java:80) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.rules.NoFragmentCycles.checkFragmentDefinition(NoFragmentCycles.java:60) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.RulesVisitor.checkFragmentDefinition(RulesVisitor.java:139) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.RulesVisitor.enter(RulesVisitor.java:59) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:31) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:34) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:26) ~[graphql-java-3.0.0.jar:na]
    at graphql.validation.Validator.validateDocument(Validator.java:20) ~[graphql-java-3.0.0.jar:na]
    at graphql.GraphQL.execute(GraphQL.java:212) ~[graphql-java-3.0.0.jar:na]
```

**Comment by bbakerman** [comment]
Just to help us reproduce and test, can you please give an example query

It helps with unit tests and reproduction  later

**Comment by tklovett** [comment]
Here is an example query (with names obscured) that causes the NPE in `NoFragmentCycles.java:67`. There may be a simpler case (maybe with less nesting) that reproduces. This example comes from our production schema.

```
query ValidationNoFragmentCyclesNPE {
  foo {
    bar {
      ...definedFragment
    }
  }
}

fragment definedFragment on Bar {
  baz {
    bang {
      bip {
        ...undefinedFragment
      }
    }
  }
}
```

Here's the affected graphql-java code:
```
private void detectCycleRecursive(String fragmentName, String initialName, List<FragmentSpread> spreadPath) {
    List<FragmentSpread> fragmentSpreads = this.fragmentSpreads.get(fragmentName);

        outer:  // EDIT: should this be here?
        for (FragmentSpread fragmentSpread : fragmentSpreads) { // EDIT: fragmentSpreads is null here, causing the NPE
```
