### ISSUE TITLE
run src/test/HelloWorld.java exception

### ISSUE THREAD

**Issue by Aidenboss** [graphql-java/graphql-java#651]
Dear:
    When I run with src/test/HelloWorld.java, I meet a exception.
   ```
    Exception in thread "main" SchemaProblem{errors=[There is no top level schema object defined]}
	at graphql.schema.idl.SchemaGenerator.makeExecutableSchema(SchemaGenerator.java:151)
	at com.HelloWorld.main(HelloWorld.java:27)
    ```

Please check it. Thanks a lot.

**Comment by andimarek** [comment]
You have to run this example with the latest version on master. 

If you are using the latest released version please have a look at the documentation: http://graphql-java.readthedocs.io/en/stable/getting_started.html 

thanks

**Comment by Aidenboss** [comment]
I am reading documentation.
Thanks a lot.
