### ISSUE TITLE
Issue when using BatchedExecutionStrategy and TracingInstrumentation together

### ISSUE THREAD

**Issue by vincentDAO** [graphql-java/graphql-java#674]
I'm using version: 4.0
I got exception when use BatchedExecutionStrategy and TracingInstrumentation together.
(Here is my single test file: https://gist.github.com/vincentDAO/81bb2fb431f2a098abf464e816671cbc)

	GraphQL graphQL1 = GraphQL.newGraphQL(schema)
		//.instrumentation(new TracingInstrumentation())
		.queryExecutionStrategy(new BatchedExecutionStrategy())
		.build();
	// work fine without instrumentation, 
	// output will be {data={viewer=6fe49fd3-84c2-4a82-adec-9229f7aa49e2}}
	String result1 = executeQuery(graphQL1, query); 
	System.out.println(result1);
	
	// if use instrumentation and BatchedExecutionStrategy together will get exception
	GraphQL graphQL2 = GraphQL.newGraphQL(schema)
		    .instrumentation(new TracingInstrumentation()) 
		    .queryExecutionStrategy(new BatchedExecutionStrategy())
		    .build();
	String result2 = executeQuery(graphQL2, query); // will throw exception
	// exception
	/*
	 * java.lang.NullPointerException: null
	at graphql.execution.instrumentation.tracing.TracingSupport.lambda$beginField$0(TracingSupport.java:67)
	at graphql.execution.instrumentation.tracing.TracingInstrumentation.lambda$beginFieldFetch$0(TracingInstrumentation.java:48)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at graphql.execution.batched.BatchedExecutionStrategy.fetchData(BatchedExecutionStrategy.java:386)
	at graphql.execution.batched.BatchedExecutionStrategy.resolveField(BatchedExecutionStrategy.java:156)
	at graphql.execution.batched.BatchedExecutionStrategy.executeImpl(BatchedExecutionStrategy.java:130)
	at graphql.execution.batched.BatchedExecutionStrategy.execute(BatchedExecutionStrategy.java:90)
	at graphql.execution.Execution.executeOperation(Execution.java:112)
	at graphql.execution.Execution.execute(Execution.java:65)
	at graphql.GraphQL.execute(GraphQL.java:466)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:414)
	at graphql.GraphQL.executeAsync(GraphQL.java:392)
	at graphql.GraphQL.execute(GraphQL.java:329)
	 */
	System.out.println(result2);
`

**Comment by bbakerman** [comment]
I can confirm this is a bug.  Its caused because the Tracing support assumes that BatchExecutionStrategy fills out the ExecutionTypeInfo correctly

            ExecutionTypeInfo typeInfo = dataFetchingEnvironment.getFieldTypeInfo();

            Map<String, Object> fetchMap = new LinkedHashMap<>();
            fetchMap.put("path", typeInfo.getPath().toList());
            fetchMap.put("parentType", typeInfo.getParentTypeInfo().toAst());
            fetchMap.put("returnType", typeInfo.toAst());
            fetchMap.put("fieldName", typeInfo.getFieldDefinition().getName());

but BatchExecutionStrategy uses it weird ways of not really knowing what field / type hierarchy is in place at one time.

We could change TracingSupport because I think the information is available elsewhere but tis really annoying that BatchedExecutionStrategy does not fill out the right ExecutionTypeInfo hierarchy correctly.

I think we need to do #675 also to fix this once and for all

**Comment by vincentDAO** [comment]
OK, thanks. 
I will follow  #675.

**Comment by vincentDAO** [comment]
hi bbakerman,
As I know you fixed this issue in #677 already.

I downloaded v4.2 but it doesn't include the fix. 

I saw you changed some lines from 85-90 in #677 https://github.com/bbakerman/graphql-java/blob/f6aacbc2a08abaf3b6fe7c1749e1f1422c3ddf34/src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java
But  the change isn't in v4.2 https://github.com/graphql-java/graphql-java/blob/v4.2/src/main/java/graphql/execution/batched/BatchedExecutionStrategy.java

Could you help to check?

**Comment by andimarek** [comment]
Hi @vincentDAO,

I am sorry, but this fix didn't make it into 4.2. (my fault)

We will release 5.0 in a few weeks, until then I recommend you use the latest development build: http://graphql-java.readthedocs.io/en/v4/getting_started.html#using-the-latest-development-build

**Comment by vincentDAO** [comment]
Thanks for you quick reply.
