### ISSUE TITLE
BatchedExecutionStrategy passes CompletableFutures to child DataFetchers as source object

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#683]
My understanding is that BatchedExecutionStrategy should support the same DataFetchers as other strategies, just that non-batched fetchers do not benefit from any batching.

But running the following example throws an exception:

```java
public void testUnbatchedAsync() {
    GraphQLSchema schema = GraphQLSchema.newSchema()
        .query(newObject()
            .name("Query")
            .field(newFieldDefinition()
                .name("user")
                .type(newObject()
                    .name("User")
                    .field(newFieldDefinition()
                        .name("id")
                        .type(new GraphQLNonNull(Scalars.GraphQLInt)))
                    .build())
                .dataFetcher(environment -> {
                    Map<String, Object> user = new HashMap<>();
                    user.put("id", 1);
                    return CompletableFuture.completedFuture(user);
                })
                .build())
            .build())
        .build();

    GraphQL graphQL = GraphQL.newGraphQL(schema)
        .queryExecutionStrategy(new BatchedExecutionStrategy())
        .build();

    ExecutionInput executionInput = ExecutionInput.newExecutionInput()
        .query("query { user { id } }")
        .build();

    ExecutionResult result = graphQL.execute(executionInput);
    Object data = result.getData();
    System.out.println(data);
}
```
```
graphql.GraphQLException: Found null value for non-null type with parent: 'User' for fields: [Field{name='id', alias='null', arguments=[], directives=[], selectionSet=null}]

	at graphql.execution.batched.BatchedExecutionStrategy.handleNonNullType(BatchedExecutionStrategy.java:254)
	at graphql.execution.batched.BatchedExecutionStrategy.completeValues(BatchedExecutionStrategy.java:174)
	at graphql.execution.batched.BatchedExecutionStrategy.lambda$resolveField$2(BatchedExecutionStrategy.java:163)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at graphql.execution.batched.BatchedExecutionStrategy.resolveField(BatchedExecutionStrategy.java:158)
	at graphql.execution.batched.BatchedExecutionStrategy.executeImpl(BatchedExecutionStrategy.java:130)
	at graphql.execution.batched.BatchedExecutionStrategy.lambda$executeImpl$1(BatchedExecutionStrategy.java:136)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at graphql.execution.batched.BatchedExecutionStrategy.executeImpl(BatchedExecutionStrategy.java:130)
	at graphql.execution.batched.BatchedExecutionStrategy.execute(BatchedExecutionStrategy.java:90)
	at graphql.execution.Execution.executeOperation(Execution.java:112)
	at graphql.execution.Execution.execute(Execution.java:65)
	at graphql.GraphQL.execute(GraphQL.java:466)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:414)
	at graphql.GraphQL.executeAsync(GraphQL.java:392)
	at graphql.GraphQL.execute(GraphQL.java:329)
```

The error happens because the field "id" uses the default `graphql.schema.PropertyDataFetcher`, which in this case gets a CompletableFuture passed in as a source, causing PropertyDataFetcher return null, as there is not "id" field in CompletableFuture.

Commenting out `.queryExecutionStrategy(new BatchedExecutionStrategy())` enables the query to complete normally.

**Comment by vincentDAO** [comment]
I think this is a bug.
It should duplicate with https://github.com/graphql-java/graphql-java/issues/672
