### ISSUE TITLE
BatchedExecutionStrategy doesn't properly handle exceptions when fetching non-null fields 

### ISSUE THREAD

**Issue by arlampin** [graphql-java/graphql-java#684]
BatchedExecutionStrategy doesn't properly handle null values for non-nullable fields if null value is the result of an exception during data fetcher execution.

The following method should run to completion and print out an error list, but instead throws an exception during execution:
```java
public void testBatchExceptions() {
    GraphQLSchema schema = GraphQLSchema.newSchema()
        .query(newObject()
            .name("Query")
            .field(newFieldDefinition()
                .name("user")
                .type(newObject()
                    .name("User")
                    .field(newFieldDefinition()
                        .name("id")
                        .type(new GraphQLNonNull(Scalars.GraphQLInt))
                        .dataFetcher(e -> {
                            throw new RuntimeException("Hello");
                        })
                    )
                    .build())
                .dataFetcher(environment -> {
                    Map<String, Object> user = new HashMap<>();
                    user.put("id", 1);
                    return user;
                })
                .build())
            .build())
        .build();

    GraphQL graphQL = GraphQL.newGraphQL(schema)
        .queryExecutionStrategy(new BatchedExecutionStrategy())
        .build();

    ExecutionInput executionInput = ExecutionInput.newExecutionInput()
        .query("query { user { id } }")
        .build();

    ExecutionResult result = graphQL.execute(executionInput);
    System.out.println(result.getErrors());
}
```
```
graphql.GraphQLException: Found null value for non-null type with parent: 'User' for fields: [Field{name='id', alias='null', arguments=[], directives=[], selectionSet=null}]

	at graphql.execution.batched.BatchedExecutionStrategy.handleNonNullType(BatchedExecutionStrategy.java:254)
	at graphql.execution.batched.BatchedExecutionStrategy.completeValues(BatchedExecutionStrategy.java:174)
	at graphql.execution.batched.BatchedExecutionStrategy.lambda$resolveField$2(BatchedExecutionStrategy.java:163)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:614)
	at java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:1983)
	at graphql.execution.batched.BatchedExecutionStrategy.resolveField(BatchedExecutionStrategy.java:158)
	at graphql.execution.batched.BatchedExecutionStrategy.executeImpl(BatchedExecutionStrategy.java:130)
	at graphql.execution.batched.BatchedExecutionStrategy.lambda$executeImpl$1(BatchedExecutionStrategy.java:136)
	at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:760)
	at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:778)
	at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2140)
	at graphql.execution.batched.BatchedExecutionStrategy.executeImpl(BatchedExecutionStrategy.java:130)
	at graphql.execution.batched.BatchedExecutionStrategy.execute(BatchedExecutionStrategy.java:90)
	at graphql.execution.Execution.executeOperation(Execution.java:112)
	at graphql.execution.Execution.execute(Execution.java:65)
	at graphql.GraphQL.execute(GraphQL.java:466)
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:414)
	at graphql.GraphQL.executeAsync(GraphQL.java:392)
	at graphql.GraphQL.execute(GraphQL.java:329)
```
Using `AsyncExecutionStrategy` or removing non-null from User.id field works as it should.

**Comment by bbakerman** [comment]
I took a quick look into this one.  The problem is that the rules on child --> parent type nullablity are not being followed

The problem code is

            resolveField(executionContext, newParameters, fieldName, curNode)
                .whenComplete((childNodes, exception) -> {
                    if (exception != null) {
                        overallResult.completeExceptionally(exception);
                        return;
                    }
                    queueOfNodes.addAll(childNodes);
                    executeImpl(executionContext, newParameters, root, finalCurNode, queueOfNodes, finalCurFieldNames, overallResult);
                });


It sees the exception (which is the wrong exception as well `graphql.execution.NonNullableFieldValidator` should be used)

We need a way to encode the type information into each place here and bubble up the parent -> child rules as discussed in http://facebook.github.io/graphql/#sec-Errors-and-Non-Nullability

Because of the way BatchedES pushes state into a shared tree it kinda challenging. Or perhaps again I dont grok how BatchedES works
