### ISSUE TITLE
MaxQueryComplexityInstrumentation not working with Union

### ISSUE THREAD

**Issue by joesankey** [graphql-java/graphql-java#699]
Using version 4.1

Get the following error when using MaxQueryComplexityInstrumentation with a schema that contains a Union:

```
graphql.schema.GraphQLUnionType cannot be cast to graphql.schema.GraphQLFieldsContainer java.lang.ClassCastException: graphql.schema.GraphQLUnionType cannot be cast to graphql.schema.GraphQLFieldsContainer
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:92)
	at graphql.analysis.QueryTraversal.visitField(QueryTraversal.java:143)
	at graphql.analysis.QueryTraversal.visitImpl(QueryTraversal.java:94)
	at graphql.analysis.QueryTraversal.visitPostOrder(QueryTraversal.java:54)
	at graphql.analysis.MaxQueryComplexityInstrumentation.lambda$beginValidation$2(MaxQueryComplexityInstrumentation.java:59)
```

**Comment by andimarek** [comment]
@joesankey thanks for reporting.

Could you also post  your Query or maybe an example derived from it? This would really help to fix that.

Thanks

**Comment by andimarek** [comment]
and also maybe you could try to use the latest development build (graphql-java.readthedocs.io/en/v4/getting_started.html#using-the-latest-development-build) ... maybe it is already fixed.

**Comment by bbakerman** [comment]
I wrote a quick unit test on this

```
    def "#699 union type in schema"() {
        given:
        def wiring = RuntimeWiring.newRuntimeWiring()
                .type(newTypeWiring("FooBar").typeResolver(new TypeResolver() {
            @Override
            GraphQLObjectType getType(TypeResolutionEnvironment env) {
                return env.getSchema().getType("Foo");
            }
        })).build()
        def schema = TestUtil.schema("""
            type Query {
                fooBar: Foo
            }
            
            union FooBar = Foo | Bar 
            
            type Bar {
                bar: String
            }  
            
            type Foo {
                foo: String
            }
        """, wiring)

        def queryStr = """
            query {
                fooBar {
                    ... on Foo {
                        foo
                    }
                }
            }
            """

        def calculator = new FieldComplexityCalculator() {
            @Override
            int calculate(FieldComplexityEnvironment environment, int childComplexity) {
                return 10
            }
        }
        MaxQueryComplexityInstrumentation queryComplexityInstrumentation = new MaxQueryComplexityInstrumentation(5, calculator)

        def graphQL = GraphQL.newGraphQL(schema).instrumentation(queryComplexityInstrumentation).build()

        def result = graphQL.execute(queryStr)

        expect:
        result.errors.size() == 1

    }
```

It works as expected in this simple case

@joesankey - can you outline more examples of why this isnt working for you please

**Comment by bbakerman** [comment]
I am going to close this for now and wait for more details to be added
