### ISSUE TITLE
NPE in ConditionalNodes when expected ExecutionInput variable is missing

### ISSUE THREAD

**Issue by tklovett** [graphql-java/graphql-java#743]
The following query will produce a NullPointerException when the `$isTrue` variable is missing.

We experienced this in our internal dev environment when a request was inadvertently missing the variables map in the JSON POST body. It is not expected to be an issue for production users/code.

```
query NPEDueToMissingVariable($isTrue: Boolean!) {
  version @include(if: $isTrue)
}
```
With ExecutionInput value:
```
ExecutionInput{query='query NPEDueToMissingVariable($isTrue: Boolean!) {
  version @include(if: $isTrue)
}
', operationName='NPEDueToMissingVariable', context=com.rmn.models.RmnContext@64ab3b49, root=null, variables={}}
```

Here's the relevant portion of the stacktrace
```
java.lang.NullPointerException: null
	at graphql.execution.ConditionalNodes.shouldInclude(ConditionalNodes.java:33) ~[graphql-java-4.1.jar:na]
	at graphql.execution.FieldCollector.collectField(FieldCollector.java:117) ~[graphql-java-4.1.jar:na]
	at graphql.execution.FieldCollector.collectFields(FieldCollector.java:80) ~[graphql-java-4.1.jar:na]
	at graphql.execution.FieldCollector.collectFields(FieldCollector.java:71) ~[graphql-java-4.1.jar:na]
	at graphql.execution.Execution.executeOperation(Execution.java:91) ~[graphql-java-4.1.jar:na]
	at graphql.execution.Execution.execute(Execution.java:65) ~[graphql-java-4.1.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:466) ~[graphql-java-4.1.jar:na]
	at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:414) ~[graphql-java-4.1.jar:na]
	at graphql.GraphQL.executeAsync(GraphQL.java:392) ~[graphql-java-4.1.jar:na]
	at graphql.GraphQL.execute(GraphQL.java:329) ~[graphql-java-4.1.jar:na]
        ...
```

And the code:

```
        if (includeDirective != null) {
            Map<String, Object> argumentValues = valuesResolver.getArgumentValues(IncludeDirective.getArguments(), includeDirective.getArguments(), variables);
            return (Boolean) argumentValues.get("if"); // argumentValues is a LinkedHashMap
        }
...
// for Map#get(Object)
     * @throws NullPointerException if the specified key is null and this map
     *         does not permit null keys
```

**Comment by bbakerman** [comment]
I wrote a unit test for this on master

```
    def "#743 missing variables"() {
        when:
        def schema = TestUtil.schema("""
            type Query {
                version : Int
            }
        """)

        def graphQL = GraphQL.newGraphQL(schema).build()

        def executionInput = ExecutionInput.newExecutionInput()
                .query('''
                    query NPEDueToMissingVariable($isTrue: Boolean!) {
                        version @include(if: $isTrue)
                    }   
                    ''')
                .variables([:])
                .build()

        graphQL.execute(executionInput)

        then:

        thrown(NonNullableValueCoercedAsNullException)
    }

```

We have improved the code around variable co-ercion to better follow spec. Note however it will still throw an exception because isTrue is defined as being a required input and yet its not present.

As such it will now throw `graphql.execution.NonNullableValueCoercedAsNullException`  which is more deliberate than a NPE but still an exception

See http://facebook.github.io/graphql/October2016/#sec-Coercing-Variable-Values

**Comment by bbakerman** [comment]
This is working as expected in 5.0
