### ISSUE TITLE
Data Fetcher Exception not shown in the result

### ISSUE THREAD

**Issue by hfye** [graphql-java/graphql-java#858]
The SimpleDataFetcherExceptionHandler is able to capture the exception, but the specific error message is not included in the return result.

This is the exception message:
WARN  SimpleDataFetcherExceptionHandler - Exception while fetching data (/addPet
) : The owner doesn't exist!
org.springframework.samples.petclinic.util.CustomRuntimeException: The owner doe
sn't exist!
        at org.springframework.samples.petclinic.graphql.resolvers.Mutation.addP
et(Mutation.java:93)
        at org.springframework.samples.petclinic.graphql.resolvers.Mutation$$Fas
tClassBySpringCGLIB$$1e529de2.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:2
04)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterce
ptor.intercept(CglibAopProxy.java:652)
        at org.springframework.samples.petclinic.graphql.resolvers.Mutation$$Enh
ancerBySpringCGLIB$$8e06e968.addPet(<generated>)
        at org.springframework.samples.petclinic.graphql.resolvers.MutationMetho
dAccess.invoke(Unknown Source)
        at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(Metho
dFieldResolver.kt:132)
        at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java
:219)
        at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.ja
va:165)
        at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrate
gy.java:55)
        at graphql.execution.Execution.executeOperation(Execution.java:154)
        at graphql.execution.Execution.execute(Execution.java:98)
        at graphql.GraphQL.execute(GraphQL.java:546)

And the return result is always like this:
{
  "data": null,
  "errors": [
    {
      "message": "Internal Server Error(s) while executing query",
      "path": null,
      "extensions": null
    }
  ]
}

**Comment by hfye** [comment]
I finally found out that the issue was caused by graphql-java-servlet. Its default error handler filtered out the errors.
