### ISSUE TITLE
Variable input type mismatch throws an AssertException

### ISSUE THREAD

**Issue by tinnou** [graphql-java/graphql-java#882]
## Issue
If a GraphQL variable refers to a non-null type that isn't defined in the schema, we raise an `AssertException` instead of a validation error.

## Steps to reproduce
The test below showcases the issue by attempting to validate a query with a variable that has an unknown type.

```groovy
def '5.7.3 Variables Are Input Types - non-null unknown type'() {
        def query = """
query madDog(\$dogCommand: UnknownType!){
    dog {
        doesKnowCommand(dogCommand: \$dogCommand)
    }
}"""
        when:
        def validationErrors = validate(query)

        then:
        !validationErrors.empty
        validationErrors.size() == 1
        validationErrors.get(0).getValidationErrorType() == ValidationErrorType.UnknownType
    }
```
will throw 

```
graphql.AssertException: wrappedType can't be null

	at graphql.Assert.assertNotNull(Assert.java:12)
	at graphql.schema.GraphQLNonNull.<init>(GraphQLNonNull.java:34)
	at graphql.execution.TypeFromAST.getTypeFromAST(TypeFromAST.java:22)
	at graphql.validation.TraversalContext.enterImpl(TraversalContext.java:141)
	at graphql.validation.TraversalContext.enter(TraversalContext.java:78)
	at graphql.validation.RulesVisitor.enter(RulesVisitor.java:58)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:33)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:36)
	at graphql.validation.LanguageTraversal.traverseImpl(LanguageTraversal.java:36)
	at graphql.validation.LanguageTraversal.traverse(LanguageTraversal.java:28)
	at graphql.validation.Validator.validateDocument(Validator.java:40)
	at graphql.validation.SpecValidationBase.validate(SpecValidationBase.groovy:18)
	at graphql.validation.SpecValidation573Test.5.7.3 Variables Are Input Types - non-null unknown type(SpecValidation573Test.groovy:49)
```

## Expected behavior

A validation error should be raised instead, similarly to what `graphql-js` does.
Here is what graphql-js returns:
```json
{
  "errors": [
    {
      "message": "Unknown type \"UnknownType\".",
      "locations": [
        {
          "line": 1,
          "column": 52
        }
      ]
    }
  ]
}```

**Comment by Edholm** [comment]
Does this also fix the issue of when an input argument is null for non-nullable types? Now I get a `NonNullableValueCoercedAsNullException` and `InternalServerError` when I would expect a validation error instead

Example that works as expected:
```
mutation {
  createItem(item: {nonNullableType:null}) {
    ...itemFields
    __typename
  }
}
```

Example that does not:
```
mutation CreateItem($item: CreateItemInput!) {
  createItem(item: $item) {
    ...itemFields
    __typename
  }
}
```
where the arguments look like this:
```
{
  "item": {
    "nonNullableType": null,
  }
}
```

**Comment by tinnou** [comment]
The issue I reported happens when the query doesn't match the schema for variable input types.

With your issue, your query seems to be valid against the schema, except the passed variable type doesn't match what your query declared. i.e `item.nonNullableType` is `null` but apparently your schema might declare it as non-null.
This is slightly different from my issue, as the variable coercion validation doesn't happen at the same place.

Also, in your case, the `NonNullableValueCoercedAsNullException` is the expected GraphQL error to be raised, and is technically a validation error. Look at this existing test that is doing exactly what you are describing https://github.com/graphql-java/graphql-java/blob/71f6fcdcfd30cac55f00cb06f88943fe773a9c08/src/test/groovy/graphql/NullVariableCoercionTest.groovy#L12

Last, graphql-java doesn't raise any `InternalServerError` so it might be the code that is calling graphql-java that is probably wrongly raising it.
